---
exclude_paths:
  - '.github/**'
  - 'CHANGELOG.md'
  - '**/CHANGELOG.md'
  - 'changelog/**'
  - '**/changelog/**'
  - 'docs/**'
  - '**/docs/**'
  - '**/pkg/proto/**'
  - 'idp/ui_config/**'
  - 'idp/scripts/**'
  - 'settings/rollup.config.js'
  - 'accounts/rollup.config.js'
  - 'deployments/**'
  - 'tests/acceptance/expected-failures-*.md'
  - 'tests/acceptance/bootstrap/**'
  - 'tests/acceptance/TestHelpers/**'
  - 'tests/acceptance/run.sh'
  - 'vendor/**/*'
  - 'tests/ociswrapper/vendor/**'
...
