---
exclude_paths:
  - '.github/**'
  - 'CHANGELOG.md'
  - '**/CHANGELOG.md'
  - 'changelog/**'
  - '**/changelog/**'
  - 'docs/**'
  - '**/docs/**'
  - '**/pkg/proto/**'
  - 'idp/ui_config/**'
  - 'idp/scripts/**'
  - 'settings/rollup.config.js'
  - 'accounts/rollup.config.js'
  - 'ocis/docker/eos-ocis/Dockerfile'
  - 'ocis/docker/eos-ocis-dev/Dockerfile'
  - 'deployments/**'
  - 'tests/acceptance/expected-failures-*.md'
  - 'tests/acceptance/bootstrap/**'

...
