#!/bin/sh

# todo: log all ocis services to stdout

echo "Waiting for EOS MGM"
echo "until nc -z -w 3 $EOS_MGM_ALIAS 1094; do sleep 2; done;" > /wait-for-mgm
chmod +x /wait-for-mgm
mkdir -p /var/log/ocis

(/wait-for-mgm; /setup > /var/log/ocis/setup.log; cat /var/log/ocis/setup.log ) &

# TODO do we still need to precreate this folder?
mkdir -p /var/tmp/reva

echo "----- [ocis] Starting oCIS -----"
# todo start ocis as daemon not as root
exec ocis server
