---
services:
  traefik:
    networks:
      ocis-ocm-net:
        aliases:
          - ${COLLABORA_OCM_DOMAIN:-collabora.ocm.owncloud.test}
          - ${WOPISERVER_OCM_DOMAIN:-wopiserver.ocm.owncloud.test}
  ocis-ocm:
    environment:
      # make collabora the secure view app
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: com.owncloud.api.collaboration.Collabora

  collaboration-ocm:
    image: ${OCIS_DOCKER_IMAGE:-owncloud/ocis}:${OCIS_DOCKER_TAG:-latest}
    networks:
      ocis-ocm-net:
    depends_on:
      ocis:
        condition: service_started
      collabora:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "ocis collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "ocis-ocm:9233"
      COLLABORATION_WOPI_SRC: https://${WOPISERVER_DOMAIN:-wopiserver.ocm.owncloud.test}
      COLLABORATION_APP_NAME: "Collabora"
      COLLABORATION_APP_ADDR: https://${COLLABORA_DOMAIN:-collabora.ocm.owncloud.test}
      COLLABORATION_APP_ICON: https://${COLLABORA_DOMAIN:-collabora.ocm.owncloud.test}/favicon.ico
      COLLABORATION_APP_INSECURE: "${INSECURE:-true}"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "${INSECURE:-true}"
      COLLABORATION_LOG_LEVEL: ${LOG_LEVEL:-debug}
      OCIS_URL: https://${OCIS_DOMAIN:-ocis.ocm.owncloud.test}
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OCIS_CONFIG_DIR:-ocis-ocm-config}:/etc/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration-ocm.entrypoints=https"
      - "traefik.http.routers.collaboration-ocm.rule=Host(`${WOPISERVER_DOMAIN:-wopiserver.ocm.owncloud.test}`)"
      - "traefik.http.routers.collaboration-ocm.tls.certresolver=http"
      - "traefik.http.routers.collaboration-ocm.service=collaboration-ocm"
      - "traefik.http.services.collaboration-ocm.loadbalancer.server.port=9300"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

  collabora-ocm:
    image: collabora/code:24.04.5.1.1
    networks:
      ocis-ocm-net:
    environment:
      aliasgroup1: https://${WOPISERVER_DOMAIN:-wopiserver.ocm.owncloud.test}:443
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=${COLLABORA_SSL_ENABLE:-true} \
        --o:ssl.ssl_verification=${COLLABORA_SSL_VERIFICATION:-true} \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=${OCIS_DOMAIN:-ocis.ocm.owncloud.test}
      username: ${COLLABORA_ADMIN_USER:-admin}
      password: ${COLLABORA_ADMIN_PASSWORD:-admin}
    cap_add:
      - MKNOD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora-ocm.entrypoints=https"
      - "traefik.http.routers.collabora-ocm.rule=Host(`${COLLABORA_DOMAIN:-collabora.ocm.owncloud.test}`)"
      - "traefik.http.routers.collabora-ocm.tls.certresolver=http"
      - "traefik.http.routers.collabora-ocm.service=collabora-ocm"
      - "traefik.http.services.collabora-ocm.loadbalancer.server.port=9980"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
    command: ["bash", "-c", "coolconfig generate-proof-key ; /start-collabora-online.sh"]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9980/hosting/discovery" ]
