services:
  ocis:
    environment:
      OCIS_MFA_ENABLED: true
      NATS_NATS_HOST: 0.0.0.0
      SETTINGS_GRPC_ADDR: ocis:9191
      OCIS_ENABLE_VAULT_MODE: true

  storage-users-vault:
    image: ${OCIS_DOCKER_IMAGE}:${OCIS_DOCKER_TAG}
    networks:
      ocis-net:
    depends_on:
      ocis:
        condition: service_started
    command: ["storage-users", "server"]
    environment:
      OCIS_LOG_LEVEL: ${LOG_LEVEL:-info}
      OCIS_LOG_COLOR: "${LOG_PRETTY:-false}"
      OCIS_LOG_PRETTY: "${LOG_PRETTY:-false}"
      OCIS_GATEWAY_GRPC_ADDR: ocis:9142
      OCIS_EVENTS_ENDPOINT: ocis:9233
      OCIS_CACHE_STORE_NODES: ocis:9233
      MICRO_REGISTRY_ADDRESS: ocis:9233
      # configure vault mode for the storage users service
      STORAGE_USERS_ENABLE_VAULT_MODE: true
      STORAGE_USERS_SERVICE_NAME: storage-users-vault
      STORAGE_USERS_GRPC_ADDR: storage-users-vault:9285
      STORAGE_USERS_HTTP_ADDR: storage-users-vault:9286
      STORAGE_USERS_DATA_SERVER_URL: http://storage-users-vault:9286/data
      STORAGE_USERS_DEBUG_ADDR: storage-users-vault:9287
      STORAGE_USERS_OCIS_ROOT: /var/lib/ocis/storage/users-vault
      STORAGE_USERS_EVENTS_CONSUMER_GROUP: vault-dcfs
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - ${OCIS_CONFIG_DIR:-ocis-config}:/etc/ocis
      - ${OCIS_DATA_DIR:-ocis-data}:/var/lib/ocis
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
