module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

require (
	github.com/haya14busa/goverage v0.0.0-20180129164344-eec3514a20b5
	golang.org/x/tools v0.1.5 // indirect
)
