module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.17

replace k8s.io/apimachinery v0.21.3 => github.com/mutagen-io/apimachinery v0.21.3-mutagen1

require github.com/mutagen-io/mutagen v0.12.0 // cmd/mutagen
