// Code generated by protoc-gen-go. DO NOT EDIT.
// source: accounts.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListAccountsRequest struct {
	// Optional. The maximum number of accounts to return in the response
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the accounts to return.
	// If no search criteria is specified then all accounts will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `email=foo@example.com` returns accounts with
	// `email` set to `foo@example.com`
	// * Query `display_name=\\"Test String\\"` returns accounts with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccountsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListAccountsRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListAccountsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListAccountsResponse struct {
	// The field name should match the noun "accounts" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ListAccountsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateAccountRequest struct {
	// The account resource to create
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type UpdateAccountRequest struct {
	// The account resource which replaces the resource on the server
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *UpdateAccountRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Account follows the properties of the ms graph api user resuorce.
// See https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
type Account struct {
	// The unique identifier for the user. Key. Not nullable. Non reassignable. Read-only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// *true* if the account is enabled; otherwise, *false*. This property is required when a user is created. Supports $filter.
	AccountEnabled bool `protobuf:"varint,2,opt,name=account_enabled,json=accountEnabled,proto3" json:"account_enabled,omitempty"`
	// A resource account is also known as a /disabled user object/ in Azure AD, and can be used to represent resources in general.
	// In Exchange it might be used to represent conference rooms, for example, and allow them to have a phone number.
	// You could give printers or machines with a sync client resource accounts as well.
	// A resource account can be homed in Microsoft 365 or on premises using Skype for Business Server 2019.
	// *true* if the user is a resource account; otherwise, *false*. Null value should be considered false.
	IsResourceAccount bool `protobuf:"varint,3,opt,name=is_resource_account,json=isResourceAccount,proto3" json:"is_resource_account,omitempty"`
	// Indicates whether the account was created as
	// - a regular school or work account ("" / emptystring),
	// - a local account, fully managed by ocis (LocalAccount), includes synced accounts or
	// - an external account (Invitation),
	// - self-service sign-up using email verification (EmailVerified). Read-only.
	CreationType string `protobuf:"bytes,4,opt,name=creation_type,json=creationType,proto3" json:"creation_type,omitempty"`
	// Represents the identities that can be used to sign in to this account.
	// An identity can be provided by OCIS (also known as a local account), by organizations, or by social identity providers such as Facebook, Google, and Microsoft, and is tied to an account.
	// May contain multiple items with the same signInType value. Supports $filter.
	Identities []*Identities `protobuf:"bytes,5,rep,name=identities,proto3" json:"identities,omitempty"`
	// The name displayed in the address book for the account.
	// This is usually the combination of the user's first name, middle initial and last name.
	// This property is required when a user is created and it cannot be cleared during updates.
	// Supports $filter and $orderby.
	// posixaccount MUST cn
	DisplayName string `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The username
	// posixaccount MUST uid
	PreferredName string `protobuf:"bytes,7,opt,name=preferred_name,json=preferredName,proto3" json:"preferred_name,omitempty"`
	// TODO rename to on_premise_? or move to extension? see https://docs.microsoft.com/en-us/graph/extensibility-open-users
	// used for exposing the user using ldap
	// posixaccount MUST uidnumber
	UidNumber int64 `protobuf:"varint,8,opt,name=uid_number,json=uidNumber,proto3" json:"uid_number,omitempty"`
	// used for exposing the user using ldap
	// posixaccount MUST gidnumber
	GidNumber int64 `protobuf:"varint,9,opt,name=gid_number,json=gidNumber,proto3" json:"gid_number,omitempty"`
	// The SMTP address for the user, for example, "jeff@contoso.onmicrosoft.com". Read-Only. Supports $filter.
	// inetorgperson MAY mail
	Mail string `protobuf:"bytes,10,opt,name=mail,proto3" json:"mail,omitempty"`
	// A description, useful for resource accounts
	// posixaccount MAY description
	Description string `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"`
	// Specifies the password profile for the user.
	// The profile contains the user’s password. This property is required when a user is created.
	// The password in the profile must satisfy minimum requirements as specified by the passwordPolicies property.
	// By default, a strong password is required.
	// posixaccount MAY authPassword
	PasswordProfile *PasswordProfile `protobuf:"bytes,12,opt,name=password_profile,json=passwordProfile,proto3" json:"password_profile,omitempty"`
	// The groups, directory roles and administrative units that the user is a member of. Read-only. Nullable.
	// should we only respond with repeated strings of ids? no clients should a proper filter mask!
	MemberOf []*Group `protobuf:"bytes,13,rep,name=memberOf,proto3" json:"memberOf,omitempty"`
	// The created date of the account object.
	CreatedDateTime *timestamp.Timestamp `protobuf:"bytes,16,opt,name=created_date_time,json=createdDateTime,proto3" json:"created_date_time,omitempty"`
	// The date and time the user was deleted. Returned only on $select.
	DeletedDateTime *timestamp.Timestamp `protobuf:"bytes,17,opt,name=deleted_date_time,json=deletedDateTime,proto3" json:"deleted_date_time,omitempty"`
	// *true* if this object is synced from an on-premises directory;
	// *false* if this object was originally synced from an on-premises directory but is no longer synced;
	// null if this object has never been synced from an on-premises directory (default). Read-only
	OnPremisesSyncEnabled bool `protobuf:"varint,20,opt,name=on_premises_sync_enabled,json=onPremisesSyncEnabled,proto3" json:"on_premises_sync_enabled,omitempty"`
	// This property is used to associate an on-premises LDAP user to the ocis account object.
	// This property must be specified when creating a new user account in the Graph if you are using a federated domain for the user’s userPrincipalName (UPN) property.
	// Important: The $ and _ characters cannot be used when specifying this property. Supports $filter.
	OnPremisesImmutableId string `protobuf:"bytes,21,opt,name=on_premises_immutable_id,json=onPremisesImmutableId,proto3" json:"on_premises_immutable_id,omitempty"`
	// Contains the on-premises security identifier (SID) for the user that was synchronized from on-premises to the cloud. Read-only.
	OnPremisesSecurityIdentifier string `protobuf:"bytes,22,opt,name=on_premises_security_identifier,json=onPremisesSecurityIdentifier,proto3" json:"on_premises_security_identifier,omitempty"`
	// Contains the on-premises LDAP `distinguished name` or `DN`.
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Read-only.
	OnPremisesDistinguishedName string `protobuf:"bytes,23,opt,name=on_premises_distinguished_name,json=onPremisesDistinguishedName,proto3" json:"on_premises_distinguished_name,omitempty"`
	// Contains the on-premises `samAccountName` synchronized from the on-premises directory.
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Read-only.
	OnPremisesSamAccountName string `protobuf:"bytes,24,opt,name=on_premises_sam_account_name,json=onPremisesSamAccountName,proto3" json:"on_premises_sam_account_name,omitempty"`
	// Contains the on-premises `domainFQDN`, also called `dnsDomainName` synchronized from the on-premises directory
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Read-only.
	OnPremisesDomainName string `protobuf:"bytes,25,opt,name=on_premises_domain_name,json=onPremisesDomainName,proto3" json:"on_premises_domain_name,omitempty"`
	// Contains the on-premises userPrincipalName synchronized from the on-premises directory.
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Read-only.
	OnPremisesUserPrincipalName string `protobuf:"bytes,26,opt,name=on_premises_user_principal_name,json=onPremisesUserPrincipalName,proto3" json:"on_premises_user_principal_name,omitempty"`
	// Indicates the last time at which the object was synced with the on-premises directory; Read-only.
	OnPremisesLastSyncDateTime *timestamp.Timestamp `protobuf:"bytes,28,opt,name=on_premises_last_sync_date_time,json=onPremisesLastSyncDateTime,proto3" json:"on_premises_last_sync_date_time,omitempty"`
	// Errors when using synchronization during provisioning.
	OnPremisesProvisioningErrors []*OnPremisesProvisioningError `protobuf:"bytes,29,rep,name=on_premises_provisioning_errors,json=onPremisesProvisioningErrors,proto3" json:"on_premises_provisioning_errors,omitempty"`
	// For an external user invited to the tenant using the invitation API, this property represents the invited user's invitation status.
	// For invited users, the state can be `PendingAcceptance` or `Accepted`, or "" / emptystring for all other users.
	// Returned only on $select. Supports $filter with the supported values. For example: $filter=externalUserState eq 'PendingAcceptance'.
	ExternalUserState string `protobuf:"bytes,40,opt,name=external_user_state,json=externalUserState,proto3" json:"external_user_state,omitempty"`
	// Shows the timestamp for the latest change to the externalUserState property. Returned only on $select.
	ExternalUserStateChangeDateTime *timestamp.Timestamp `protobuf:"bytes,41,opt,name=external_user_state_change_date_time,json=externalUserStateChangeDateTime,proto3" json:"external_user_state_change_date_time,omitempty"`
	// Any refresh tokens or sessions tokens (session cookies) issued before this time are invalid, and applications will get
	// an error when using an invalid refresh or sessions token to acquire a delegated access token (to access APIs such as Microsoft Graph).
	// If this happens, the application will need to acquire a new refresh token by making a request to the authorize endpoint.
	// Returned only on $select. Read-only. Use invalidateAllRefreshTokens to reset.
	RefreshTokensValidFromDateTime *timestamp.Timestamp `protobuf:"bytes,60,opt,name=refresh_tokens_valid_from_date_time,json=refreshTokensValidFromDateTime,proto3" json:"refresh_tokens_valid_from_date_time,omitempty"`
	// Any refresh tokens or sessions tokens (session cookies) issued before this time are invalid, and applications will get
	// an error when using an invalid refresh or sessions token to acquire a delegated access token (to access APIs such as Microsoft Graph).
	// If this happens, the application will need to acquire a new refresh token by making a request to the authorize endpoint.
	// Read-only. Use revokeSignInSessions to reset.
	SignInSessionsValidFromDateTime *timestamp.Timestamp `protobuf:"bytes,61,opt,name=sign_in_sessions_valid_from_date_time,json=signInSessionsValidFromDateTime,proto3" json:"sign_in_sessions_valid_from_date_time,omitempty"`
	XXX_NoUnkeyedLiteral            struct{}             `json:"-"`
	XXX_unrecognized                []byte               `json:"-"`
	XXX_sizecache                   int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetAccountEnabled() bool {
	if m != nil {
		return m.AccountEnabled
	}
	return false
}

func (m *Account) GetIsResourceAccount() bool {
	if m != nil {
		return m.IsResourceAccount
	}
	return false
}

func (m *Account) GetCreationType() string {
	if m != nil {
		return m.CreationType
	}
	return ""
}

func (m *Account) GetIdentities() []*Identities {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *Account) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Account) GetPreferredName() string {
	if m != nil {
		return m.PreferredName
	}
	return ""
}

func (m *Account) GetUidNumber() int64 {
	if m != nil {
		return m.UidNumber
	}
	return 0
}

func (m *Account) GetGidNumber() int64 {
	if m != nil {
		return m.GidNumber
	}
	return 0
}

func (m *Account) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *Account) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Account) GetPasswordProfile() *PasswordProfile {
	if m != nil {
		return m.PasswordProfile
	}
	return nil
}

func (m *Account) GetMemberOf() []*Group {
	if m != nil {
		return m.MemberOf
	}
	return nil
}

func (m *Account) GetCreatedDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedDateTime
	}
	return nil
}

func (m *Account) GetDeletedDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedDateTime
	}
	return nil
}

func (m *Account) GetOnPremisesSyncEnabled() bool {
	if m != nil {
		return m.OnPremisesSyncEnabled
	}
	return false
}

func (m *Account) GetOnPremisesImmutableId() string {
	if m != nil {
		return m.OnPremisesImmutableId
	}
	return ""
}

func (m *Account) GetOnPremisesSecurityIdentifier() string {
	if m != nil {
		return m.OnPremisesSecurityIdentifier
	}
	return ""
}

func (m *Account) GetOnPremisesDistinguishedName() string {
	if m != nil {
		return m.OnPremisesDistinguishedName
	}
	return ""
}

func (m *Account) GetOnPremisesSamAccountName() string {
	if m != nil {
		return m.OnPremisesSamAccountName
	}
	return ""
}

func (m *Account) GetOnPremisesDomainName() string {
	if m != nil {
		return m.OnPremisesDomainName
	}
	return ""
}

func (m *Account) GetOnPremisesUserPrincipalName() string {
	if m != nil {
		return m.OnPremisesUserPrincipalName
	}
	return ""
}

func (m *Account) GetOnPremisesLastSyncDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.OnPremisesLastSyncDateTime
	}
	return nil
}

func (m *Account) GetOnPremisesProvisioningErrors() []*OnPremisesProvisioningError {
	if m != nil {
		return m.OnPremisesProvisioningErrors
	}
	return nil
}

func (m *Account) GetExternalUserState() string {
	if m != nil {
		return m.ExternalUserState
	}
	return ""
}

func (m *Account) GetExternalUserStateChangeDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExternalUserStateChangeDateTime
	}
	return nil
}

func (m *Account) GetRefreshTokensValidFromDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.RefreshTokensValidFromDateTime
	}
	return nil
}

func (m *Account) GetSignInSessionsValidFromDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.SignInSessionsValidFromDateTime
	}
	return nil
}

// Identities Represents an identity used to sign in to a user account.
// An identity can be provided by ocis, by organizations, or by social identity providers such as Facebook, Google, or Microsoft, that are tied to a user account.
// This enables the user to sign in to the user account with any of those associated identities.
// They are also used to keep a history of old usernames.
type Identities struct {
	// Specifies the user sign-in types in your directory, such as `emailAddress`, `userName` or `federated`.
	// Here, federated represents a unique identifier for a user from an issuer, that can be in any format chosen by the issuer.
	// Additional validation is enforced on *issuer_assigned_id* when the sign-in type is set to `emailAddress` or `userName`.
	// This property can also be set to any custom string.
	SignInType string `protobuf:"bytes,1,opt,name=sign_in_type,json=signInType,proto3" json:"sign_in_type,omitempty"`
	// Specifies the issuer of the identity, for example facebook.com.
	// For local accounts (where signInType is not federated), this property is
	// the local B2C tenant default domain name, for example contoso.onmicrosoft.com.
	// For external users from other Azure AD organization, this will be the domain of
	// the federated organization, for example contoso.com.
	// Supports $filter. 512 character limit.
	Issuer string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Specifies the unique identifier assigned to the user by the issuer. The combination of *issuer* and *issuerAssignedId* must be unique within the organization. Represents the sign-in name for the user, when signInType is set to emailAddress or userName (also known as local accounts).
	// When *signInType* is set to:
	// * `emailAddress`, (or starts with `emailAddress` like `emailAddress1`) *issuerAssignedId* must be a valid email address
	// * `userName`, issuer_assigned_id must be a valid local part of an email address
	// Supports $filter. 512 character limit.
	IssuerAssignedId     string   `protobuf:"bytes,3,opt,name=issuer_assigned_id,json=issuerAssignedId,proto3" json:"issuer_assigned_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identities) Reset()         { *m = Identities{} }
func (m *Identities) String() string { return proto.CompactTextString(m) }
func (*Identities) ProtoMessage()    {}
func (*Identities) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{7}
}

func (m *Identities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identities.Unmarshal(m, b)
}
func (m *Identities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identities.Marshal(b, m, deterministic)
}
func (m *Identities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identities.Merge(m, src)
}
func (m *Identities) XXX_Size() int {
	return xxx_messageInfo_Identities.Size(m)
}
func (m *Identities) XXX_DiscardUnknown() {
	xxx_messageInfo_Identities.DiscardUnknown(m)
}

var xxx_messageInfo_Identities proto.InternalMessageInfo

func (m *Identities) GetSignInType() string {
	if m != nil {
		return m.SignInType
	}
	return ""
}

func (m *Identities) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *Identities) GetIssuerAssignedId() string {
	if m != nil {
		return m.IssuerAssignedId
	}
	return ""
}

type PasswordProfile struct {
	//	The password for the user. This property is required when a user is created.
	// It can be updated, but the user will be required to change the password on the next login.
	// The password must satisfy minimum requirements as specified by the user’s passwordPolicies property. By default, a strong password is required.
	Password string `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	// The time when this account last changed their password.
	LastPasswordChangeDateTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_password_change_date_time,json=lastPasswordChangeDateTime,proto3" json:"last_password_change_date_time,omitempty"`
	// Specifies password policies for the user.
	//This value is an enumeration with one possible value being “DisableStrongPassword”, which allows weaker passwords than the default policy to be specified.
	// “DisablePasswordExpiration” can also be specified.
	PasswordPolicies []string `protobuf:"bytes,3,rep,name=password_policies,json=passwordPolicies,proto3" json:"password_policies,omitempty"`
	// *true* if the user must change her password on the next login; otherwise false.
	ForceChangePasswordNextSignIn bool `protobuf:"varint,4,opt,name=force_change_password_next_sign_in,json=forceChangePasswordNextSignIn,proto3" json:"force_change_password_next_sign_in,omitempty"`
	// If *true*, at next sign-in, the user must perform a multi-factor authentication (MFA) before being forced to change their password. The behavior is identical to forceChangePasswordNextSignIn except that the user is required to first perform a multi-factor authentication before password change. After a password change, this property will be automatically reset to false. If not set, default is false.
	ForceChangePasswordNextSignInWithMfa bool     `protobuf:"varint,5,opt,name=force_change_password_next_sign_in_with_mfa,json=forceChangePasswordNextSignInWithMfa,proto3" json:"force_change_password_next_sign_in_with_mfa,omitempty"`
	XXX_NoUnkeyedLiteral                 struct{} `json:"-"`
	XXX_unrecognized                     []byte   `json:"-"`
	XXX_sizecache                        int32    `json:"-"`
}

func (m *PasswordProfile) Reset()         { *m = PasswordProfile{} }
func (m *PasswordProfile) String() string { return proto.CompactTextString(m) }
func (*PasswordProfile) ProtoMessage()    {}
func (*PasswordProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{8}
}

func (m *PasswordProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordProfile.Unmarshal(m, b)
}
func (m *PasswordProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordProfile.Marshal(b, m, deterministic)
}
func (m *PasswordProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordProfile.Merge(m, src)
}
func (m *PasswordProfile) XXX_Size() int {
	return xxx_messageInfo_PasswordProfile.Size(m)
}
func (m *PasswordProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordProfile.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordProfile proto.InternalMessageInfo

func (m *PasswordProfile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PasswordProfile) GetLastPasswordChangeDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastPasswordChangeDateTime
	}
	return nil
}

func (m *PasswordProfile) GetPasswordPolicies() []string {
	if m != nil {
		return m.PasswordPolicies
	}
	return nil
}

func (m *PasswordProfile) GetForceChangePasswordNextSignIn() bool {
	if m != nil {
		return m.ForceChangePasswordNextSignIn
	}
	return false
}

func (m *PasswordProfile) GetForceChangePasswordNextSignInWithMfa() bool {
	if m != nil {
		return m.ForceChangePasswordNextSignInWithMfa
	}
	return false
}

type ListGroupsRequest struct {
	// Optional. The maximum number of groups to return in the response
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the groups to return.
	// If no search criteria is specified then all groups will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `display_name=\\"Test String\\"` returns groups with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{9}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListGroupsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListGroupsRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListGroupsRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListGroupsResponse struct {
	// The field name should match the noun "group" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{10}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *ListGroupsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetGroupRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupRequest) Reset()         { *m = GetGroupRequest{} }
func (m *GetGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetGroupRequest) ProtoMessage()    {}
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{11}
}

func (m *GetGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupRequest.Unmarshal(m, b)
}
func (m *GetGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupRequest.Merge(m, src)
}
func (m *GetGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetGroupRequest.Size(m)
}
func (m *GetGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupRequest proto.InternalMessageInfo

func (m *GetGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateGroupRequest struct {
	// The account resource to create
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{12}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type UpdateGroupRequest struct {
	// The group resource which replaces the resource on the server
	Group *Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// The update mask applies to the resource. For the `FieldMask` definition,
	// see https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateGroupRequest) Reset()         { *m = UpdateGroupRequest{} }
func (m *UpdateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupRequest) ProtoMessage()    {}
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{13}
}

func (m *UpdateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupRequest.Unmarshal(m, b)
}
func (m *UpdateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupRequest.Marshal(b, m, deterministic)
}
func (m *UpdateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupRequest.Merge(m, src)
}
func (m *UpdateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupRequest.Size(m)
}
func (m *UpdateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupRequest proto.InternalMessageInfo

func (m *UpdateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *UpdateGroupRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteGroupRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{14}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddMemberRequest struct {
	// The account id to add
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddMemberRequest) Reset()         { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()    {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{15}
}

func (m *AddMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddMemberRequest.Unmarshal(m, b)
}
func (m *AddMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddMemberRequest.Marshal(b, m, deterministic)
}
func (m *AddMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddMemberRequest.Merge(m, src)
}
func (m *AddMemberRequest) XXX_Size() int {
	return xxx_messageInfo_AddMemberRequest.Size(m)
}
func (m *AddMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddMemberRequest proto.InternalMessageInfo

func (m *AddMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveMemberRequest struct {
	// The account id to remove
	// TODO id in the body indt in the url? not necessary ... use empty?
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMemberRequest) Reset()         { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()    {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{16}
}

func (m *RemoveMemberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMemberRequest.Unmarshal(m, b)
}
func (m *RemoveMemberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMemberRequest.Marshal(b, m, deterministic)
}
func (m *RemoveMemberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMemberRequest.Merge(m, src)
}
func (m *RemoveMemberRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveMemberRequest.Size(m)
}
func (m *RemoveMemberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMemberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMemberRequest proto.InternalMessageInfo

func (m *RemoveMemberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListMembersRequest struct {
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. A pagination token returned from a previous call to `Get`
	// that indicates from where search should continue
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Used to specify a subset of fields that should be
	// returned by a get operation or modified by an update operation.
	FieldMask *field_mask.FieldMask `protobuf:"bytes,3,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	// Optional. Search criteria used to select the groups to return.
	// If no search criteria is specified then all groups will be
	// returned
	//
	// TODO update query language
	// Query expressions can be used to restrict results based upon
	// the account properties where the operators `=`, `NOT`, `AND` and `OR`
	// can be used along with the suffix wildcard symbol `*`.
	//
	// The string properties in a query expression should use escaped quotes
	// for values that include whitespace to prevent unexpected behavior.
	//
	// Some example queries are:
	//
	// * Query `display_name=Th*` returns accounts whose display_name
	// starts with "Th"
	// * Query `display_name=\\"Test String\\"` returns groups with
	// display names that include both "Test" and "String"
	Query                string   `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersRequest) Reset()         { *m = ListMembersRequest{} }
func (m *ListMembersRequest) String() string { return proto.CompactTextString(m) }
func (*ListMembersRequest) ProtoMessage()    {}
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{17}
}

func (m *ListMembersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersRequest.Unmarshal(m, b)
}
func (m *ListMembersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersRequest.Marshal(b, m, deterministic)
}
func (m *ListMembersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersRequest.Merge(m, src)
}
func (m *ListMembersRequest) XXX_Size() int {
	return xxx_messageInfo_ListMembersRequest.Size(m)
}
func (m *ListMembersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersRequest proto.InternalMessageInfo

func (m *ListMembersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListMembersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListMembersRequest) GetFieldMask() *field_mask.FieldMask {
	if m != nil {
		return m.FieldMask
	}
	return nil
}

func (m *ListMembersRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListMembersResponse struct {
	// The field name should match the noun "members" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request
	Members []*Account `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMembersResponse) Reset()         { *m = ListMembersResponse{} }
func (m *ListMembersResponse) String() string { return proto.CompactTextString(m) }
func (*ListMembersResponse) ProtoMessage()    {}
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{18}
}

func (m *ListMembersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMembersResponse.Unmarshal(m, b)
}
func (m *ListMembersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMembersResponse.Marshal(b, m, deterministic)
}
func (m *ListMembersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMembersResponse.Merge(m, src)
}
func (m *ListMembersResponse) XXX_Size() int {
	return xxx_messageInfo_ListMembersResponse.Size(m)
}
func (m *ListMembersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMembersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMembersResponse proto.InternalMessageInfo

func (m *ListMembersResponse) GetMembers() []*Account {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *ListMembersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type Group struct {
	// The unique identifier for the group.
	// Returned by default. Inherited from directoryObject. Key. Not nullable. Read-only.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name for the group. This property is required when a group is created and cannot be cleared during updates.
	// Returned by default. Supports $filter and $orderby.
	// groupofnames MUST cn
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Users, contacts, and groups that are members of this group. HTTP Methods: GET (supported for all groups), POST (supported for security groups and mail-enabled security groups), DELETE (supported only for security groups) Read-only. Nullable.
	// TODO accounts (users) only for now, we can add groups with the dedicated message using oneof construct later
	Members []*Account `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// groupofnames MAY businessCategory
	// groupofnames MAY o
	// groupofnames MAY ou
	// groupofnames MAY owner, SINGLE-VALUE but there might be multiple owners
	Owners []*Account `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
	// An optional description for the group. Returned by default.
	// groupofnames MAY description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// used for exposing the user using ldap
	// posixgroup MUST gidnumber
	GidNumber int64 `protobuf:"varint,6,opt,name=gid_number,json=gidNumber,proto3" json:"gid_number,omitempty"`
	// Timestamp of when the group was created. The value cannot be modified and is automatically populated when the group is created
	// Returned by default. Read-only.
	CreatedDateTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_date_time,json=createdDateTime,proto3" json:"created_date_time,omitempty"`
	// For some Azure Active Directory objects (user, group, application), if the object is deleted, it is first logically deleted, and this property is updated with the date and time when the object was deleted. Otherwise this property is null. If the object is restored, this property is updated to null.
	// Returned by default. Read-only.
	DeletedDateTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=deleted_date_time,json=deletedDateTime,proto3" json:"deleted_date_time,omitempty"`
	// Timestamp of when the group is set to expire. The value cannot be modified and is automatically populated when the group is created.
	// Returned by default. Read-only.
	ExpirationDateTime *timestamp.Timestamp `protobuf:"bytes,9,opt,name=expiration_date_time,json=expirationDateTime,proto3" json:"expiration_date_time,omitempty"`
	// True if the group is not displayed in certain parts of the Outlook user interface:
	// in the Address Book, in address lists for selecting message recipients, and in the Browse Groups dialog for searching groups; false otherwise. Default value is false.
	// Returned only on $select.
	HideFromAddressLists bool `protobuf:"varint,10,opt,name=hide_from_address_lists,json=hideFromAddressLists,proto3" json:"hide_from_address_lists,omitempty"`
	// 	Specifies the visibility of an Office 365 group. Possible values are: Private, Public, or Hiddenmembership; blank values are treated as public. See group visibility options to learn more.
	// Visibility can be set only when a group is created; it is not editable.
	// Returned by default.
	Visibility string `protobuf:"bytes,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// *true* if this group is synced from an on-premises directory;
	// *false* if this group was originally synced from an on-premises directory but is no longer synced;
	// null if this object has never been synced from an on-premises directory (default).
	// Returned by default. Read-only. Supports $filter.
	OnPremisesSyncEnabled bool `protobuf:"varint,20,opt,name=on_premises_sync_enabled,json=onPremisesSyncEnabled,proto3" json:"on_premises_sync_enabled,omitempty"`
	// This property is used to associate an on-premises LDAP user to the ocis account object.
	// This property must be specified when creating a new user account in the Graph if you are using a federated domain for the user’s userPrincipalName (UPN) property.
	// Important: The $ and _ characters cannot be used when specifying this property. Supports $filter.
	OnPremisesImmutableId string `protobuf:"bytes,21,opt,name=on_premises_immutable_id,json=onPremisesImmutableId,proto3" json:"on_premises_immutable_id,omitempty"`
	// Contains the on-premises security identifier (SID) for the group that was synchronized from on-premises to the cloud. Returned by default. Read-only.
	OnPremisesSecurityIdentifier string `protobuf:"bytes,22,opt,name=on_premises_security_identifier,json=onPremisesSecurityIdentifier,proto3" json:"on_premises_security_identifier,omitempty"`
	// Contains the on-premises LDAP `distinguished name` or `DN`.
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Read-only.
	OnPremisesDistinguishedName string `protobuf:"bytes,23,opt,name=on_premises_distinguished_name,json=onPremisesDistinguishedName,proto3" json:"on_premises_distinguished_name,omitempty"`
	// Contains the on-premises `samAccountName` synchronized from the on-premises directory.
	// The property is only populated for customers who are synchronizing their on-premises directory to ocis-accounts. Returned by default. Read-only.
	OnPremisesSamAccountName string `protobuf:"bytes,24,opt,name=on_premises_sam_account_name,json=onPremisesSamAccountName,proto3" json:"on_premises_sam_account_name,omitempty"`
	// Contains the on-premises domain FQDN, also called dnsDomainName synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect.
	// Returned by default. Read-only.
	OnPremisesDomainName string `protobuf:"bytes,25,opt,name=on_premises_domain_name,json=onPremisesDomainName,proto3" json:"on_premises_domain_name,omitempty"`
	// 	Contains the on-premises netBios name synchronized from the on-premises directory. The property is only populated for customers who are synchronizing their on-premises directory to Azure Active Directory via Azure AD Connect.
	// Returned by default. Read-only.
	OnPremisesNetBiosName string `protobuf:"bytes,26,opt,name=on_premises_net_bios_name,json=onPremisesNetBiosName,proto3" json:"on_premises_net_bios_name,omitempty"`
	// Indicates the last time at which the group was synced with the on-premises directory.
	// Returned by default. Read-only. Supports $filter.
	OnPremisesLastSyncDateTime string `protobuf:"bytes,27,opt,name=on_premises_last_sync_date_time,json=onPremisesLastSyncDateTime,proto3" json:"on_premises_last_sync_date_time,omitempty"`
	// Errors when using synchronization during provisioning.
	OnPremisesProvisioningErrors []*OnPremisesProvisioningError `protobuf:"bytes,28,rep,name=on_premises_provisioning_errors,json=onPremisesProvisioningErrors,proto3" json:"on_premises_provisioning_errors,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                       `json:"-"`
	XXX_unrecognized             []byte                         `json:"-"`
	XXX_sizecache                int32                          `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{19}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Group) GetMembers() []*Account {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetOwners() []*Account {
	if m != nil {
		return m.Owners
	}
	return nil
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Group) GetGidNumber() int64 {
	if m != nil {
		return m.GidNumber
	}
	return 0
}

func (m *Group) GetCreatedDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedDateTime
	}
	return nil
}

func (m *Group) GetDeletedDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedDateTime
	}
	return nil
}

func (m *Group) GetExpirationDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.ExpirationDateTime
	}
	return nil
}

func (m *Group) GetHideFromAddressLists() bool {
	if m != nil {
		return m.HideFromAddressLists
	}
	return false
}

func (m *Group) GetVisibility() string {
	if m != nil {
		return m.Visibility
	}
	return ""
}

func (m *Group) GetOnPremisesSyncEnabled() bool {
	if m != nil {
		return m.OnPremisesSyncEnabled
	}
	return false
}

func (m *Group) GetOnPremisesImmutableId() string {
	if m != nil {
		return m.OnPremisesImmutableId
	}
	return ""
}

func (m *Group) GetOnPremisesSecurityIdentifier() string {
	if m != nil {
		return m.OnPremisesSecurityIdentifier
	}
	return ""
}

func (m *Group) GetOnPremisesDistinguishedName() string {
	if m != nil {
		return m.OnPremisesDistinguishedName
	}
	return ""
}

func (m *Group) GetOnPremisesSamAccountName() string {
	if m != nil {
		return m.OnPremisesSamAccountName
	}
	return ""
}

func (m *Group) GetOnPremisesDomainName() string {
	if m != nil {
		return m.OnPremisesDomainName
	}
	return ""
}

func (m *Group) GetOnPremisesNetBiosName() string {
	if m != nil {
		return m.OnPremisesNetBiosName
	}
	return ""
}

func (m *Group) GetOnPremisesLastSyncDateTime() string {
	if m != nil {
		return m.OnPremisesLastSyncDateTime
	}
	return ""
}

func (m *Group) GetOnPremisesProvisioningErrors() []*OnPremisesProvisioningError {
	if m != nil {
		return m.OnPremisesProvisioningErrors
	}
	return nil
}

type OnPremisesProvisioningError struct {
	// Category of the provisioning error. Note: Currently, there is only one possible value. Possible value: PropertyConflict - indicates a property value is not unique. Other objects contain the same value for the property.
	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	// The date and time at which the error occurred.
	OccurredDateTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=occurred_date_time,json=occurredDateTime,proto3" json:"occurred_date_time,omitempty"`
	// Name of the directory property causing the error. Current possible values: UserPrincipalName or ProxyAddress
	PropertyCausingError string `protobuf:"bytes,3,opt,name=property_causing_error,json=propertyCausingError,proto3" json:"property_causing_error,omitempty"`
	// Value of the property causing the error.
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnPremisesProvisioningError) Reset()         { *m = OnPremisesProvisioningError{} }
func (m *OnPremisesProvisioningError) String() string { return proto.CompactTextString(m) }
func (*OnPremisesProvisioningError) ProtoMessage()    {}
func (*OnPremisesProvisioningError) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{20}
}

func (m *OnPremisesProvisioningError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnPremisesProvisioningError.Unmarshal(m, b)
}
func (m *OnPremisesProvisioningError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnPremisesProvisioningError.Marshal(b, m, deterministic)
}
func (m *OnPremisesProvisioningError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnPremisesProvisioningError.Merge(m, src)
}
func (m *OnPremisesProvisioningError) XXX_Size() int {
	return xxx_messageInfo_OnPremisesProvisioningError.Size(m)
}
func (m *OnPremisesProvisioningError) XXX_DiscardUnknown() {
	xxx_messageInfo_OnPremisesProvisioningError.DiscardUnknown(m)
}

var xxx_messageInfo_OnPremisesProvisioningError proto.InternalMessageInfo

func (m *OnPremisesProvisioningError) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *OnPremisesProvisioningError) GetOccurredDateTime() *timestamp.Timestamp {
	if m != nil {
		return m.OccurredDateTime
	}
	return nil
}

func (m *OnPremisesProvisioningError) GetPropertyCausingError() string {
	if m != nil {
		return m.PropertyCausingError
	}
	return ""
}

func (m *OnPremisesProvisioningError) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ListAccountsRequest)(nil), "settings.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "settings.ListAccountsResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "settings.GetAccountRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "settings.CreateAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "settings.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "settings.DeleteAccountRequest")
	proto.RegisterType((*Account)(nil), "settings.Account")
	proto.RegisterType((*Identities)(nil), "settings.Identities")
	proto.RegisterType((*PasswordProfile)(nil), "settings.PasswordProfile")
	proto.RegisterType((*ListGroupsRequest)(nil), "settings.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "settings.ListGroupsResponse")
	proto.RegisterType((*GetGroupRequest)(nil), "settings.GetGroupRequest")
	proto.RegisterType((*CreateGroupRequest)(nil), "settings.CreateGroupRequest")
	proto.RegisterType((*UpdateGroupRequest)(nil), "settings.UpdateGroupRequest")
	proto.RegisterType((*DeleteGroupRequest)(nil), "settings.DeleteGroupRequest")
	proto.RegisterType((*AddMemberRequest)(nil), "settings.AddMemberRequest")
	proto.RegisterType((*RemoveMemberRequest)(nil), "settings.RemoveMemberRequest")
	proto.RegisterType((*ListMembersRequest)(nil), "settings.ListMembersRequest")
	proto.RegisterType((*ListMembersResponse)(nil), "settings.ListMembersResponse")
	proto.RegisterType((*Group)(nil), "settings.Group")
	proto.RegisterType((*OnPremisesProvisioningError)(nil), "settings.OnPremisesProvisioningError")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 1951 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0x5b, 0x4f, 0x1c, 0xc9,
	0x15, 0xd6, 0x80, 0x81, 0xe1, 0x0c, 0x18, 0x28, 0xc6, 0xd0, 0x0c, 0x17, 0xcf, 0xb6, 0x8d, 0x17,
	0xc3, 0x06, 0x2c, 0xb2, 0x9b, 0x8b, 0x9d, 0x8d, 0x84, 0xc1, 0x76, 0x90, 0x6c, 0x2f, 0x1a, 0xbc,
	0x59, 0xe5, 0xa2, 0x6d, 0x35, 0xdd, 0x35, 0x43, 0xad, 0xa7, 0x2f, 0x5b, 0x55, 0x3d, 0x66, 0x36,
	0x5a, 0x29, 0xca, 0x53, 0xde, 0xf2, 0x90, 0x1f, 0x92, 0xcb, 0x1f, 0xc9, 0x43, 0xfe, 0xc0, 0x3e,
	0xe4, 0x29, 0xbf, 0x22, 0xaa, 0x4b, 0x77, 0xd7, 0x74, 0xcf, 0x30, 0xbb, 0xf1, 0x4a, 0x91, 0xa5,
	0x3c, 0xd1, 0x5d, 0xe7, 0x3b, 0xdf, 0x39, 0x75, 0xea, 0x4c, 0xd5, 0xd7, 0x05, 0xdc, 0x74, 0x3d,
	0x2f, 0x4a, 0x42, 0xce, 0xf6, 0x63, 0x1a, 0xf1, 0x08, 0x55, 0x19, 0xe6, 0x9c, 0x84, 0x1d, 0xd6,
	0xb8, 0xdd, 0x89, 0xa2, 0x4e, 0x17, 0x1f, 0xb8, 0x31, 0x39, 0x68, 0x13, 0xdc, 0xf5, 0x9d, 0x0b,
	0x7c, 0xe9, 0xf6, 0x48, 0x44, 0x15, 0xb4, 0xb1, 0x61, 0x00, 0xdc, 0x30, 0x8c, 0xb8, 0xcb, 0x49,
	0x14, 0x6a, 0xa2, 0xc6, 0xba, 0xb6, 0xca, 0xb7, 0x8b, 0xa4, 0x7d, 0x80, 0x83, 0x98, 0xf7, 0xb5,
	0xb1, 0x59, 0x34, 0xaa, 0x00, 0x81, 0xcb, 0x5e, 0x6b, 0xc4, 0xed, 0x22, 0x82, 0x93, 0x00, 0x33,
	0xee, 0x06, 0xb1, 0x02, 0xd8, 0x7f, 0xab, 0xc0, 0xf2, 0x73, 0xc2, 0xf8, 0x91, 0xce, 0xbf, 0x85,
	0xbf, 0x4c, 0x30, 0xe3, 0xa8, 0x09, 0xb3, 0xb1, 0xdb, 0xc1, 0x0e, 0x23, 0x5f, 0x61, 0xab, 0xd2,
	0xac, 0xec, 0x4c, 0x3d, 0x9e, 0xfc, 0xe6, 0xa8, 0xd2, 0xaa, 0x8a, 0xd1, 0x73, 0xf2, 0x15, 0x46,
	0x36, 0x80, 0x44, 0xf0, 0xe8, 0x35, 0x0e, 0xad, 0x89, 0x66, 0x65, 0x67, 0x56, 0x41, 0xa4, 0xe3,
	0x2b, 0x31, 0x8a, 0x7e, 0x0a, 0x90, 0xa7, 0x64, 0x4d, 0x36, 0x2b, 0x3b, 0xb5, 0xc3, 0xc6, 0xbe,
	0xca, 0x69, 0x3f, 0xcd, 0x69, 0xff, 0xa9, 0x80, 0xbc, 0x70, 0xd9, 0xeb, 0xd6, 0x6c, 0x3b, 0x7d,
	0x44, 0x6b, 0x30, 0xf5, 0x65, 0x82, 0x69, 0xdf, 0xba, 0x91, 0x33, 0xab, 0x11, 0x3b, 0x80, 0xfa,
	0x60, 0xca, 0x2c, 0x8e, 0x42, 0x86, 0xd1, 0x0f, 0xa0, 0x9a, 0x2e, 0x83, 0x55, 0x69, 0x4e, 0xee,
	0xd4, 0x0e, 0x97, 0xf6, 0xd3, 0x75, 0xd8, 0xd7, 0xe8, 0x56, 0x06, 0x41, 0xf7, 0x60, 0x21, 0xc4,
	0x57, 0xdc, 0x29, 0xce, 0xa2, 0x35, 0x2f, 0x86, 0xcf, 0xd2, 0x49, 0xd8, 0x77, 0x60, 0xe9, 0x19,
	0x4e, 0xa3, 0xa5, 0xf5, 0xb9, 0x09, 0x13, 0xc4, 0x97, 0x85, 0x99, 0x6d, 0x4d, 0x10, 0xdf, 0x3e,
	0x86, 0xfa, 0x31, 0xc5, 0x2e, 0xc7, 0x05, 0xdc, 0x1e, 0xcc, 0xe8, 0x80, 0x12, 0x3c, 0x34, 0xa5,
	0x14, 0x61, 0xff, 0xbe, 0x02, 0xf5, 0x4f, 0x63, 0xff, 0xed, 0x58, 0xd0, 0x23, 0xa8, 0x25, 0x92,
	0x44, 0x55, 0x7d, 0x62, 0x6c, 0xd5, 0x41, 0xc1, 0xc5, 0xb3, 0x7d, 0x0f, 0xea, 0x27, 0xb8, 0x8b,
	0x4b, 0x19, 0x14, 0xe7, 0xfb, 0xc7, 0x79, 0x98, 0xd1, 0x90, 0xa2, 0x0d, 0xbd, 0x0f, 0x0b, 0x3a,
	0x17, 0x07, 0x87, 0xee, 0x45, 0x17, 0xfb, 0x32, 0x89, 0x6a, 0x2b, 0xfd, 0x95, 0x3c, 0x51, 0xa3,
	0x68, 0x1f, 0x96, 0x09, 0x73, 0x28, 0x66, 0x51, 0x42, 0x3d, 0xec, 0xa4, 0x53, 0x9c, 0x94, 0xe0,
	0x25, 0x22, 0x56, 0x56, 0x5a, 0xd2, 0x40, 0x77, 0x60, 0xde, 0x13, 0x45, 0x26, 0x51, 0xe8, 0xf0,
	0x7e, 0x8c, 0x55, 0x6f, 0xb4, 0xe6, 0xd2, 0xc1, 0x57, 0xfd, 0x18, 0xa3, 0x0f, 0x01, 0x88, 0x8f,
	0x43, 0x4e, 0x38, 0xc1, 0xcc, 0x9a, 0x92, 0x7d, 0x50, 0xcf, 0xcb, 0x75, 0x9a, 0xd9, 0x5a, 0x06,
	0x0e, 0xbd, 0x07, 0x73, 0x3e, 0x61, 0x71, 0xd7, 0xed, 0x3b, 0xa1, 0x1b, 0x60, 0x6b, 0x5a, 0x32,
	0xd7, 0xf4, 0xd8, 0x4b, 0x37, 0xc0, 0x68, 0x1b, 0x6e, 0xc6, 0x14, 0xb7, 0x31, 0xa5, 0xd8, 0x57,
	0xa0, 0x19, 0xd5, 0x2e, 0xd9, 0xa8, 0x84, 0x6d, 0x02, 0x24, 0xc4, 0x77, 0xc2, 0x24, 0xb8, 0xc0,
	0xd4, 0xaa, 0x36, 0x2b, 0x3b, 0x93, 0xad, 0xd9, 0x84, 0xf8, 0x2f, 0xe5, 0x80, 0x30, 0x77, 0x72,
	0xf3, 0xac, 0x32, 0x77, 0x32, 0x33, 0x82, 0x1b, 0x81, 0x4b, 0xba, 0x16, 0x48, 0x6a, 0xf9, 0x8c,
	0x9a, 0x50, 0xf3, 0x31, 0xf3, 0x28, 0x89, 0xc5, 0x24, 0xad, 0x9a, 0x4e, 0x2d, 0x1f, 0x42, 0x27,
	0xb0, 0x18, 0xbb, 0x8c, 0xbd, 0x89, 0xa8, 0xef, 0xc4, 0x34, 0x6a, 0x93, 0x2e, 0xb6, 0xe6, 0xe4,
	0xba, 0xaf, 0xe5, 0x33, 0x3f, 0xd3, 0x88, 0x33, 0x05, 0x68, 0x2d, 0xc4, 0x83, 0x03, 0x68, 0x0f,
	0xaa, 0x01, 0x16, 0x59, 0x7c, 0xd2, 0xb6, 0xe6, 0x65, 0xdd, 0x16, 0x72, 0xef, 0x67, 0x34, 0x4a,
	0xe2, 0x56, 0x06, 0x40, 0x4f, 0x61, 0x49, 0x96, 0x1d, 0xfb, 0x8e, 0xec, 0x35, 0xb1, 0xb1, 0x58,
	0x8b, 0x23, 0x7a, 0xed, 0x55, 0xba, 0xeb, 0xb4, 0x16, 0xb4, 0xd3, 0x89, 0xcb, 0xb1, 0x18, 0x15,
	0x3c, 0xbe, 0x6c, 0x38, 0x93, 0x67, 0x69, 0x3c, 0x8f, 0x76, 0xca, 0x78, 0x7e, 0x0c, 0x56, 0x14,
	0x3a, 0x31, 0xc5, 0x01, 0x61, 0x98, 0x39, 0xac, 0x1f, 0x7a, 0x59, 0xf7, 0xd5, 0x65, 0x43, 0xdd,
	0x8a, 0xc2, 0x33, 0x6d, 0x3e, 0xef, 0x87, 0x5e, 0xda, 0x84, 0x05, 0x47, 0x12, 0x04, 0x09, 0x17,
	0x16, 0x87, 0xf8, 0xd6, 0x2d, 0x59, 0x6a, 0xc3, 0xf1, 0x34, 0xb5, 0x9e, 0xfa, 0xe8, 0x09, 0xdc,
	0x1e, 0x88, 0x88, 0xbd, 0x84, 0x12, 0xde, 0x77, 0x54, 0x57, 0xb5, 0x09, 0xa6, 0xd6, 0x8a, 0xf4,
	0xdf, 0x30, 0x02, 0x6b, 0xd0, 0x69, 0x86, 0x41, 0xc7, 0xb0, 0x65, 0xd2, 0xf8, 0x84, 0x89, 0x82,
	0x27, 0x84, 0x5d, 0xa6, 0x6d, 0xb6, 0x2a, 0x59, 0xd6, 0x73, 0x96, 0x13, 0x13, 0x23, 0x9b, 0xee,
	0xe7, 0xb0, 0x31, 0x90, 0x8b, 0x1b, 0xa4, 0xbf, 0x26, 0x45, 0x61, 0x49, 0x0a, 0xcb, 0x48, 0xc4,
	0x0d, 0xf4, 0xaf, 0x4a, 0xfa, 0x7f, 0x04, 0xab, 0x03, 0x49, 0x44, 0x81, 0x4b, 0x42, 0xe5, 0xba,
	0x26, 0x5d, 0xeb, 0x46, 0x74, 0x69, 0x94, 0x6e, 0x27, 0x83, 0x25, 0x48, 0x18, 0xa6, 0x4e, 0x4c,
	0x49, 0xe8, 0x91, 0xd8, 0xed, 0x2a, 0xf7, 0x46, 0x31, 0xf9, 0x4f, 0x19, 0xa6, 0x67, 0x29, 0x46,
	0xb2, 0x38, 0x83, 0x2c, 0x5d, 0x97, 0x71, 0xb5, 0x7e, 0x79, 0x43, 0x6c, 0x8c, 0x6d, 0x88, 0x46,
	0x1e, 0xe1, 0xb9, 0xcb, 0xb8, 0x58, 0xe1, 0xac, 0x37, 0xba, 0x83, 0x01, 0x62, 0x1a, 0xf5, 0x08,
	0x23, 0x51, 0x48, 0xc2, 0x8e, 0x83, 0x29, 0x8d, 0x28, 0xb3, 0x36, 0x65, 0xbf, 0x6f, 0xe7, 0xfd,
	0xfe, 0x49, 0x46, 0x77, 0x66, 0xc0, 0x9f, 0x08, 0xb4, 0xb9, 0xa0, 0x25, 0x23, 0x13, 0xbb, 0x1a,
	0xbe, 0xe2, 0x98, 0x86, 0x6e, 0x57, 0x55, 0x84, 0x71, 0x97, 0x63, 0x6b, 0x47, 0x16, 0x62, 0x29,
	0x35, 0x89, 0x32, 0x9c, 0x0b, 0x03, 0x22, 0x70, 0x77, 0x08, 0xde, 0xf1, 0x2e, 0xdd, 0xb0, 0x83,
	0x8d, 0x1a, 0xdc, 0x1f, 0x5b, 0x83, 0xdb, 0x25, 0xf2, 0x63, 0x49, 0x92, 0x15, 0xa2, 0x03, 0x77,
	0x28, 0x6e, 0x53, 0xcc, 0x2e, 0xd5, 0x81, 0xc7, 0x9c, 0x9e, 0xdb, 0x25, 0xbe, 0xd3, 0xa6, 0x51,
	0x60, 0x44, 0xfa, 0xd9, 0xd8, 0x48, 0x5b, 0x9a, 0x46, 0x9e, 0x90, 0xec, 0x97, 0x82, 0xe4, 0x29,
	0x8d, 0x82, 0x2c, 0xd0, 0x17, 0xb0, 0xcd, 0x48, 0x27, 0x74, 0x48, 0xe8, 0x30, 0xcc, 0x44, 0x7d,
	0x46, 0x84, 0xfa, 0x78, 0xfc, 0xa4, 0x04, 0xd1, 0x69, 0x78, 0xae, 0x69, 0x4a, 0xb1, 0x6c, 0x0e,
	0x90, 0x6f, 0xea, 0xa8, 0x09, 0x73, 0x69, 0x64, 0x79, 0x44, 0xa8, 0x63, 0x09, 0x14, 0x89, 0x3c,
	0x20, 0x56, 0x60, 0x9a, 0x30, 0x96, 0x60, 0xaa, 0x8f, 0x7b, 0xfd, 0x86, 0x3e, 0x00, 0xa4, 0x9e,
	0x1c, 0x97, 0x09, 0x38, 0xf6, 0xc5, 0x16, 0x30, 0x29, 0x31, 0x8b, 0xca, 0x72, 0xa4, 0x0d, 0xa7,
	0xbe, 0xfd, 0xcd, 0x04, 0x2c, 0x14, 0x76, 0x54, 0xd4, 0x80, 0x6a, 0xba, 0xa7, 0xea, 0xb8, 0xd9,
	0x3b, 0xfa, 0x1c, 0xb6, 0x64, 0x63, 0x67, 0xfb, 0x74, 0x69, 0x7d, 0x27, 0xc6, 0xf7, 0xb8, 0x60,
	0x48, 0x83, 0x16, 0x96, 0x76, 0x0f, 0x96, 0xf2, 0x23, 0x20, 0xea, 0x12, 0x4f, 0x9c, 0x7e, 0x93,
	0xcd, 0x49, 0x91, 0x7c, 0xb6, 0xd1, 0xeb, 0x71, 0x74, 0x0a, 0x76, 0x3b, 0x12, 0x47, 0xae, 0x4e,
	0x22, 0xf3, 0x94, 0x82, 0x48, 0xd7, 0x4f, 0x9e, 0xae, 0xd5, 0xd6, 0xa6, 0x44, 0xaa, 0x68, 0x69,
	0xec, 0x97, 0xf8, 0x8a, 0x9f, 0xcb, 0x8a, 0xa2, 0x5f, 0xc1, 0xde, 0x78, 0x2a, 0xe7, 0x0d, 0xe1,
	0x97, 0x4e, 0xd0, 0x76, 0xad, 0x29, 0xc9, 0x79, 0xf7, 0x5a, 0xce, 0xcf, 0x08, 0xbf, 0x7c, 0xd1,
	0x76, 0xed, 0xbf, 0x54, 0x60, 0x49, 0x08, 0x3d, 0x79, 0xf4, 0xbc, 0x13, 0xca, 0x14, 0x03, 0x32,
	0x13, 0xd6, 0xba, 0xf4, 0x7d, 0x98, 0xee, 0xc8, 0x11, 0xad, 0x4a, 0x4b, 0xa7, 0xaa, 0x36, 0x7f,
	0x6b, 0x45, 0xfa, 0x1e, 0x2c, 0x3c, 0xc3, 0x2a, 0xca, 0x28, 0x7d, 0xf6, 0x08, 0x90, 0xd2, 0xa3,
	0x03, 0xa8, 0x6d, 0x98, 0x92, 0xa1, 0xb4, 0x8a, 0x2c, 0x25, 0xa2, 0xac, 0xf6, 0x15, 0x20, 0x25,
	0x43, 0xff, 0x0b, 0xe7, 0xb7, 0x93, 0x9f, 0x77, 0x01, 0x29, 0xf9, 0x79, 0xed, 0xe4, 0x6c, 0x58,
	0x3c, 0xf2, 0xfd, 0x17, 0x52, 0x8a, 0x8c, 0xc2, 0x6c, 0xc3, 0x72, 0x0b, 0x07, 0x51, 0x0f, 0x5f,
	0x0f, 0xfb, 0x6b, 0x45, 0x2d, 0x99, 0x42, 0xbd, 0x13, 0x4d, 0xf6, 0x85, 0xfa, 0x62, 0xcb, 0x32,
	0xd6, 0x5d, 0xb6, 0x07, 0x33, 0x4a, 0x9c, 0x5d, 0xf3, 0xf1, 0x93, 0x22, 0xbe, 0x75, 0xa7, 0xfd,
	0xbb, 0x0a, 0x53, 0x72, 0x29, 0x4a, 0x22, 0xbf, 0x28, 0x98, 0x27, 0xca, 0x82, 0xd9, 0xc8, 0x68,
	0x72, 0x6c, 0x46, 0xf7, 0x61, 0x3a, 0x7a, 0x13, 0x0a, 0xec, 0x8d, 0x51, 0x58, 0x0d, 0x28, 0xea,
	0xe1, 0xa9, 0xb2, 0x1e, 0x1e, 0x14, 0xd9, 0xd3, 0x45, 0x91, 0x3d, 0x54, 0xbb, 0xce, 0x7c, 0x4f,
	0xda, 0xb5, 0xfa, 0xdd, 0xb5, 0xeb, 0x73, 0xa8, 0xe3, 0xab, 0x98, 0x50, 0xf5, 0x65, 0x93, 0x53,
	0xcd, 0x8e, 0xa5, 0x42, 0xb9, 0x5f, 0xc6, 0xf6, 0x11, 0xac, 0x5e, 0x12, 0x1f, 0xab, 0x93, 0xd6,
	0xf5, 0x7d, 0x8a, 0x19, 0x73, 0xba, 0x84, 0x71, 0x26, 0xbf, 0x2a, 0xaa, 0xad, 0xba, 0x30, 0x8b,
	0x23, 0xf4, 0x48, 0x19, 0x45, 0x37, 0x31, 0xb4, 0x05, 0x20, 0x94, 0xcc, 0x05, 0xe9, 0x12, 0xde,
	0xd7, 0x1f, 0x19, 0xc6, 0xc8, 0xff, 0x05, 0xf6, 0xff, 0x42, 0x60, 0xff, 0x04, 0xd6, 0x4c, 0xb7,
	0x10, 0x73, 0xe7, 0x82, 0x44, 0xcc, 0x94, 0xd6, 0x46, 0xf1, 0x5e, 0x62, 0xfe, 0x98, 0x44, 0x4c,
	0x7a, 0x1e, 0x8f, 0x17, 0xd5, 0xeb, 0xd2, 0xff, 0x2d, 0x85, 0xf3, 0xc6, 0xf7, 0x26, 0x9c, 0xed,
	0x7f, 0x54, 0x60, 0xfd, 0x1a, 0x6f, 0x21, 0xaf, 0x3c, 0x97, 0xe3, 0x4e, 0x44, 0xfb, 0xa9, 0xbc,
	0x4a, 0xdf, 0xd1, 0x2f, 0x00, 0x45, 0x9e, 0x97, 0xc8, 0x6f, 0xf3, 0xef, 0x22, 0xa9, 0x16, 0x53,
	0xaf, 0x6c, 0xce, 0x1f, 0xc2, 0x4a, 0x4c, 0xa3, 0x18, 0x53, 0xde, 0x77, 0x3c, 0x37, 0x61, 0xd9,
	0x5c, 0xb5, 0x14, 0xac, 0xa7, 0xd6, 0x63, 0x65, 0x54, 0xb9, 0xd5, 0x61, 0xaa, 0xe7, 0x76, 0x93,
	0xf4, 0x4a, 0x42, 0xbd, 0x1c, 0xfe, 0xe9, 0x06, 0x2c, 0xa4, 0xd7, 0x54, 0xe7, 0x98, 0xf6, 0x88,
	0x87, 0x91, 0x07, 0x73, 0xe6, 0xed, 0x15, 0xda, 0xcc, 0x4b, 0x37, 0xe4, 0x22, 0xae, 0xb1, 0x35,
	0xca, 0xac, 0xb6, 0x7d, 0xbb, 0xfe, 0x87, 0x7f, 0xfe, 0xeb, 0xcf, 0x13, 0x37, 0xd1, 0xdc, 0x41,
	0xef, 0xc1, 0x41, 0x76, 0xb7, 0xf5, 0x5b, 0x80, 0xfc, 0xce, 0x0a, 0xad, 0x1b, 0x47, 0x75, 0xf1,
	0x26, 0xab, 0x51, 0xde, 0x68, 0xed, 0x2d, 0xc9, 0x69, 0xa1, 0x65, 0x93, 0xf3, 0xe0, 0x77, 0xc4,
	0xff, 0x78, 0xf7, 0xeb, 0x87, 0x95, 0x5d, 0xe4, 0xc2, 0xfc, 0xc0, 0x65, 0x17, 0x32, 0x92, 0x1c,
	0x76, 0x0b, 0x36, 0x2c, 0xc6, 0xa6, 0x8c, 0xb1, 0x6a, 0x0f, 0xe4, 0xfd, 0x30, 0xbb, 0xc4, 0x8a,
	0x61, 0x7e, 0xe0, 0x26, 0xcc, 0x0c, 0x31, 0xec, 0x8a, 0x6c, 0x58, 0x88, 0x0f, 0x64, 0x88, 0x7b,
	0x87, 0xeb, 0x83, 0xd3, 0xd0, 0x4f, 0xfb, 0x6a, 0x3a, 0x59, 0x44, 0x1f, 0xe6, 0x07, 0x6e, 0xbe,
	0xcc, 0x88, 0xc3, 0xae, 0xc4, 0x1a, 0x2b, 0xa5, 0xb6, 0x7a, 0x12, 0xc4, 0xbc, 0x6f, 0xaf, 0xcb,
	0xb0, 0xb7, 0x76, 0x87, 0x55, 0xef, 0xf0, 0xef, 0xd3, 0x30, 0xaf, 0xe4, 0x61, 0xda, 0x0f, 0xbf,
	0x01, 0xc8, 0x35, 0xa3, 0xb9, 0x54, 0x25, 0xe9, 0xdb, 0xd8, 0x18, 0x6e, 0xd4, 0x9d, 0x80, 0x64,
	0xdc, 0x39, 0x04, 0x22, 0xae, 0x56, 0x94, 0xaf, 0xa0, 0x9a, 0x2a, 0x45, 0xb4, 0x36, 0xd0, 0x05,
	0xa6, 0xc0, 0x6a, 0x14, 0xb5, 0x9c, 0xbd, 0x21, 0xb9, 0x56, 0xd0, 0x52, 0xce, 0x65, 0xac, 0xff,
	0x67, 0x50, 0x33, 0xc4, 0x25, 0xda, 0x28, 0xae, 0xfe, 0xf5, 0xdc, 0x6b, 0x92, 0x7b, 0xd9, 0x36,
	0xf2, 0x7c, 0xa8, 0xb5, 0xa3, 0x0f, 0x35, 0x43, 0x78, 0x9a, 0xc4, 0x65, 0x3d, 0x5a, 0x26, 0xbe,
	0x27, 0x89, 0x9b, 0x87, 0xab, 0x66, 0xd2, 0xf2, 0xaf, 0x5e, 0x6b, 0x1d, 0xe5, 0x73, 0xa8, 0x19,
	0x22, 0xd3, 0x8c, 0x52, 0xd6, 0x9e, 0x23, 0x57, 0x59, 0xcf, 0x62, 0xb7, 0x5c, 0x21, 0xe4, 0xc1,
	0x6c, 0x26, 0x4f, 0x51, 0xc3, 0xe8, 0xcb, 0x82, 0x66, 0x2d, 0xcf, 0xe0, 0xbe, 0x24, 0xbd, 0x63,
	0x6f, 0x95, 0x48, 0x0f, 0xb4, 0x4e, 0x3a, 0xb8, 0x4b, 0x71, 0x5b, 0xac, 0x41, 0x0f, 0xe6, 0x4c,
	0x7d, 0x6b, 0x6e, 0x23, 0x43, 0x74, 0x6f, 0x39, 0xd4, 0x8f, 0x64, 0xa8, 0x07, 0xbb, 0x7b, 0xa3,
	0x43, 0x19, 0xbf, 0x94, 0xaf, 0xb3, 0xb8, 0x14, 0x6a, 0x86, 0xfa, 0x44, 0x85, 0x96, 0x1c, 0x94,
	0xd1, 0x8d, 0xcd, 0x11, 0x56, 0xdd, 0xb1, 0x7a, 0xc1, 0xd0, 0x98, 0xe9, 0x3e, 0xae, 0xff, 0x1a,
	0xc5, 0xaf, 0x3b, 0xea, 0x9f, 0x18, 0x07, 0xbd, 0x07, 0x8f, 0xd4, 0x52, 0x4c, 0xcb, 0x3f, 0x3f,
	0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x7b, 0x5d, 0x05, 0x7c, 0x19, 0x00, 0x00,
}
