// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/v0/accounts.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Payload              *Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Record) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Payload struct {
	Phoenix              *Phoenix `protobuf:"bytes,1,opt,name=phoenix,proto3" json:"phoenix,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetPhoenix() *Phoenix {
	if m != nil {
		return m.Phoenix
	}
	return nil
}

func (m *Payload) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type Account struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,2,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{2}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

type Phoenix struct {
	Theme                string   `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phoenix) Reset()         { *m = Phoenix{} }
func (m *Phoenix) String() string { return proto.CompactTextString(m) }
func (*Phoenix) ProtoMessage()    {}
func (*Phoenix) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{3}
}

func (m *Phoenix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phoenix.Unmarshal(m, b)
}
func (m *Phoenix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phoenix.Marshal(b, m, deterministic)
}
func (m *Phoenix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phoenix.Merge(m, src)
}
func (m *Phoenix) XXX_Size() int {
	return xxx_messageInfo_Phoenix.Size(m)
}
func (m *Phoenix) XXX_DiscardUnknown() {
	xxx_messageInfo_Phoenix.DiscardUnknown(m)
}

var xxx_messageInfo_Phoenix proto.InternalMessageInfo

func (m *Phoenix) GetTheme() string {
	if m != nil {
		return m.Theme
	}
	return ""
}

type Query struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{4}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Records struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Records) Reset()         { *m = Records{} }
func (m *Records) String() string { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()    {}
func (*Records) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3c84319968a576b, []int{5}
}

func (m *Records) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Records.Unmarshal(m, b)
}
func (m *Records) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Records.Marshal(b, m, deterministic)
}
func (m *Records) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Records.Merge(m, src)
}
func (m *Records) XXX_Size() int {
	return xxx_messageInfo_Records.Size(m)
}
func (m *Records) XXX_DiscardUnknown() {
	xxx_messageInfo_Records.DiscardUnknown(m)
}

var xxx_messageInfo_Records proto.InternalMessageInfo

func (m *Records) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "settings.Record")
	proto.RegisterType((*Payload)(nil), "settings.Payload")
	proto.RegisterType((*Account)(nil), "settings.Account")
	proto.RegisterType((*Phoenix)(nil), "settings.Phoenix")
	proto.RegisterType((*Query)(nil), "settings.Query")
	proto.RegisterType((*Records)(nil), "settings.Records")
}

func init() { proto.RegisterFile("pkg/proto/v0/accounts.proto", fileDescriptor_e3c84319968a576b) }

var fileDescriptor_e3c84319968a576b = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0x53, 0x0b, 0xac, 0x0c, 0x07, 0x60, 0x62, 0x0c, 0xc2, 0xc1, 0xa6, 0xa7, 0xaa, 0x49,
	0xab, 0x18, 0xcf, 0x46, 0x12, 0xc3, 0xc5, 0x44, 0x5d, 0x6e, 0xde, 0x6a, 0x19, 0x4a, 0x03, 0x74,
	0x9b, 0x76, 0x21, 0xf6, 0xa7, 0xf8, 0x6f, 0x0d, 0xbb, 0x5d, 0x51, 0xeb, 0xa9, 0xd3, 0xf7, 0xbe,
	0x99, 0x7d, 0x99, 0x81, 0x51, 0xb6, 0x8a, 0x83, 0x2c, 0x17, 0x52, 0x04, 0xbb, 0xeb, 0x20, 0x8c,
	0x22, 0xb1, 0x4d, 0x65, 0xe1, 0x2b, 0x05, 0x8f, 0x0b, 0x92, 0x32, 0x49, 0xe3, 0x62, 0x38, 0x8a,
	0x85, 0x88, 0xd7, 0xa4, 0xc9, 0xf7, 0xed, 0x22, 0xa0, 0x4d, 0x26, 0x4b, 0x8d, 0xb9, 0x53, 0x68,
	0x71, 0x8a, 0x44, 0x3e, 0xc7, 0x1e, 0xd8, 0x2b, 0x2a, 0x07, 0x96, 0x63, 0x79, 0x6d, 0xbe, 0x2f,
	0xf1, 0x0a, 0x58, 0x16, 0x96, 0x6b, 0x11, 0xce, 0x07, 0x47, 0x8e, 0xe5, 0x75, 0xc6, 0x7d, 0xdf,
	0x0c, 0xf5, 0x5f, 0xb4, 0xc1, 0x0d, 0xe1, 0x46, 0xc0, 0x2a, 0x4d, 0xf5, 0x2d, 0x05, 0xa5, 0xc9,
	0x87, 0x9a, 0xf6, 0xbb, 0x4f, 0x1b, 0xdc, 0x10, 0x7b, 0xb8, 0x4a, 0x5e, 0x7f, 0xe4, 0x41, 0x1b,
	0xdc, 0x10, 0xee, 0x3d, 0xb0, 0x4a, 0x43, 0x84, 0x46, 0x1a, 0x6e, 0xa8, 0xca, 0xab, 0x6a, 0x74,
	0xa0, 0x33, 0x0f, 0x25, 0x3d, 0x2f, 0x26, 0x49, 0x2e, 0x97, 0x6a, 0x5e, 0x9b, 0xff, 0x94, 0xdc,
	0x73, 0x60, 0x55, 0x02, 0x3c, 0x81, 0xa6, 0x5c, 0xd2, 0xf7, 0x04, 0xfd, 0xe3, 0x9e, 0x41, 0xf3,
	0x75, 0x4b, 0x79, 0x59, 0x5f, 0x87, 0x7b, 0x07, 0x4c, 0xaf, 0xaa, 0xc0, 0x4b, 0x60, 0xb9, 0x2e,
	0x07, 0x96, 0x63, 0x7b, 0x9d, 0x71, 0xef, 0x10, 0x5a, 0x33, 0xdc, 0x00, 0xe3, 0x4f, 0x0b, 0xba,
	0xb3, 0xca, 0x9c, 0x51, 0xbe, 0x4b, 0x22, 0xc2, 0x0b, 0xb0, 0x67, 0x24, 0xb1, 0xd6, 0x35, 0xac,
	0x29, 0xe8, 0x81, 0x3d, 0x25, 0x89, 0xdd, 0x83, 0xa1, 0xf2, 0xfd, 0x43, 0xde, 0x40, 0xe3, 0x29,
	0x29, 0x24, 0x9e, 0xfa, 0xfa, 0xe0, 0xbe, 0x39, 0xb8, 0xff, 0xb8, 0x3f, 0xf8, 0xb0, 0xff, 0xb7,
	0xa3, 0x98, 0xb0, 0xb7, 0xa6, 0x86, 0x5a, 0xea, 0x73, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x06,
	0x2e, 0xab, 0xa7, 0x53, 0x02, 0x00, 0x00,
}
