// Code generated by protoc-gen-go. DO NOT EDIT.
// source: settings.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// requests and responses
type CreateSettingsBundleRequest struct {
	SettingsBundle       *SettingsBundle `protobuf:"bytes,1,opt,name=settings_bundle,json=settingsBundle,proto3" json:"settings_bundle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateSettingsBundleRequest) Reset()         { *m = CreateSettingsBundleRequest{} }
func (m *CreateSettingsBundleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSettingsBundleRequest) ProtoMessage()    {}
func (*CreateSettingsBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{0}
}

func (m *CreateSettingsBundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSettingsBundleRequest.Unmarshal(m, b)
}
func (m *CreateSettingsBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSettingsBundleRequest.Marshal(b, m, deterministic)
}
func (m *CreateSettingsBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSettingsBundleRequest.Merge(m, src)
}
func (m *CreateSettingsBundleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSettingsBundleRequest.Size(m)
}
func (m *CreateSettingsBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSettingsBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSettingsBundleRequest proto.InternalMessageInfo

func (m *CreateSettingsBundleRequest) GetSettingsBundle() *SettingsBundle {
	if m != nil {
		return m.SettingsBundle
	}
	return nil
}

type CreateSettingsBundleResponse struct {
	SettingsBundle       *SettingsBundle `protobuf:"bytes,1,opt,name=settings_bundle,json=settingsBundle,proto3" json:"settings_bundle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateSettingsBundleResponse) Reset()         { *m = CreateSettingsBundleResponse{} }
func (m *CreateSettingsBundleResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSettingsBundleResponse) ProtoMessage()    {}
func (*CreateSettingsBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{1}
}

func (m *CreateSettingsBundleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSettingsBundleResponse.Unmarshal(m, b)
}
func (m *CreateSettingsBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSettingsBundleResponse.Marshal(b, m, deterministic)
}
func (m *CreateSettingsBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSettingsBundleResponse.Merge(m, src)
}
func (m *CreateSettingsBundleResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSettingsBundleResponse.Size(m)
}
func (m *CreateSettingsBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSettingsBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSettingsBundleResponse proto.InternalMessageInfo

func (m *CreateSettingsBundleResponse) GetSettingsBundle() *SettingsBundle {
	if m != nil {
		return m.SettingsBundle
	}
	return nil
}

type GetSettingsBundleRequest struct {
	Extension            string   `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSettingsBundleRequest) Reset()         { *m = GetSettingsBundleRequest{} }
func (m *GetSettingsBundleRequest) String() string { return proto.CompactTextString(m) }
func (*GetSettingsBundleRequest) ProtoMessage()    {}
func (*GetSettingsBundleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{2}
}

func (m *GetSettingsBundleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSettingsBundleRequest.Unmarshal(m, b)
}
func (m *GetSettingsBundleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSettingsBundleRequest.Marshal(b, m, deterministic)
}
func (m *GetSettingsBundleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSettingsBundleRequest.Merge(m, src)
}
func (m *GetSettingsBundleRequest) XXX_Size() int {
	return xxx_messageInfo_GetSettingsBundleRequest.Size(m)
}
func (m *GetSettingsBundleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSettingsBundleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSettingsBundleRequest proto.InternalMessageInfo

func (m *GetSettingsBundleRequest) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *GetSettingsBundleRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetSettingsBundleResponse struct {
	SettingsBundle       *SettingsBundle `protobuf:"bytes,1,opt,name=settings_bundle,json=settingsBundle,proto3" json:"settings_bundle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetSettingsBundleResponse) Reset()         { *m = GetSettingsBundleResponse{} }
func (m *GetSettingsBundleResponse) String() string { return proto.CompactTextString(m) }
func (*GetSettingsBundleResponse) ProtoMessage()    {}
func (*GetSettingsBundleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{3}
}

func (m *GetSettingsBundleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSettingsBundleResponse.Unmarshal(m, b)
}
func (m *GetSettingsBundleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSettingsBundleResponse.Marshal(b, m, deterministic)
}
func (m *GetSettingsBundleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSettingsBundleResponse.Merge(m, src)
}
func (m *GetSettingsBundleResponse) XXX_Size() int {
	return xxx_messageInfo_GetSettingsBundleResponse.Size(m)
}
func (m *GetSettingsBundleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSettingsBundleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSettingsBundleResponse proto.InternalMessageInfo

func (m *GetSettingsBundleResponse) GetSettingsBundle() *SettingsBundle {
	if m != nil {
		return m.SettingsBundle
	}
	return nil
}

type ListSettingsBundlesRequest struct {
	Extension            string   `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSettingsBundlesRequest) Reset()         { *m = ListSettingsBundlesRequest{} }
func (m *ListSettingsBundlesRequest) String() string { return proto.CompactTextString(m) }
func (*ListSettingsBundlesRequest) ProtoMessage()    {}
func (*ListSettingsBundlesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{4}
}

func (m *ListSettingsBundlesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSettingsBundlesRequest.Unmarshal(m, b)
}
func (m *ListSettingsBundlesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSettingsBundlesRequest.Marshal(b, m, deterministic)
}
func (m *ListSettingsBundlesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSettingsBundlesRequest.Merge(m, src)
}
func (m *ListSettingsBundlesRequest) XXX_Size() int {
	return xxx_messageInfo_ListSettingsBundlesRequest.Size(m)
}
func (m *ListSettingsBundlesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSettingsBundlesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSettingsBundlesRequest proto.InternalMessageInfo

func (m *ListSettingsBundlesRequest) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

type ListSettingsBundlesResponse struct {
	SettingsBundles      []*SettingsBundle `protobuf:"bytes,1,rep,name=settings_bundles,json=settingsBundles,proto3" json:"settings_bundles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListSettingsBundlesResponse) Reset()         { *m = ListSettingsBundlesResponse{} }
func (m *ListSettingsBundlesResponse) String() string { return proto.CompactTextString(m) }
func (*ListSettingsBundlesResponse) ProtoMessage()    {}
func (*ListSettingsBundlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{5}
}

func (m *ListSettingsBundlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSettingsBundlesResponse.Unmarshal(m, b)
}
func (m *ListSettingsBundlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSettingsBundlesResponse.Marshal(b, m, deterministic)
}
func (m *ListSettingsBundlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSettingsBundlesResponse.Merge(m, src)
}
func (m *ListSettingsBundlesResponse) XXX_Size() int {
	return xxx_messageInfo_ListSettingsBundlesResponse.Size(m)
}
func (m *ListSettingsBundlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSettingsBundlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSettingsBundlesResponse proto.InternalMessageInfo

func (m *ListSettingsBundlesResponse) GetSettingsBundles() []*SettingsBundle {
	if m != nil {
		return m.SettingsBundles
	}
	return nil
}

// payloads
type SettingsBundle struct {
	Extension            string     `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	Key                  string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	DisplayName          string     `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Settings             []*Setting `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SettingsBundle) Reset()         { *m = SettingsBundle{} }
func (m *SettingsBundle) String() string { return proto.CompactTextString(m) }
func (*SettingsBundle) ProtoMessage()    {}
func (*SettingsBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{6}
}

func (m *SettingsBundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsBundle.Unmarshal(m, b)
}
func (m *SettingsBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsBundle.Marshal(b, m, deterministic)
}
func (m *SettingsBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsBundle.Merge(m, src)
}
func (m *SettingsBundle) XXX_Size() int {
	return xxx_messageInfo_SettingsBundle.Size(m)
}
func (m *SettingsBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsBundle.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsBundle proto.InternalMessageInfo

func (m *SettingsBundle) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *SettingsBundle) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SettingsBundle) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *SettingsBundle) GetSettings() []*Setting {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Setting struct {
	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Setting_IntValue
	//	*Setting_StringValue
	//	*Setting_BoolValue
	//	*Setting_SingleChoiceValue
	//	*Setting_MultiChoiceValue
	Value                isSetting_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Setting) Reset()         { *m = Setting{} }
func (m *Setting) String() string { return proto.CompactTextString(m) }
func (*Setting) ProtoMessage()    {}
func (*Setting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{7}
}

func (m *Setting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Setting.Unmarshal(m, b)
}
func (m *Setting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Setting.Marshal(b, m, deterministic)
}
func (m *Setting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Setting.Merge(m, src)
}
func (m *Setting) XXX_Size() int {
	return xxx_messageInfo_Setting.Size(m)
}
func (m *Setting) XXX_DiscardUnknown() {
	xxx_messageInfo_Setting.DiscardUnknown(m)
}

var xxx_messageInfo_Setting proto.InternalMessageInfo

func (m *Setting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Setting) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Setting) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type isSetting_Value interface {
	isSetting_Value()
}

type Setting_IntValue struct {
	IntValue *IntSetting `protobuf:"bytes,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Setting_StringValue struct {
	StringValue *StringSetting `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Setting_BoolValue struct {
	BoolValue *BoolSetting `protobuf:"bytes,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Setting_SingleChoiceValue struct {
	SingleChoiceValue *SingleChoiceListSetting `protobuf:"bytes,7,opt,name=single_choice_value,json=singleChoiceValue,proto3,oneof"`
}

type Setting_MultiChoiceValue struct {
	MultiChoiceValue *MultiChoiceListSetting `protobuf:"bytes,8,opt,name=multi_choice_value,json=multiChoiceValue,proto3,oneof"`
}

func (*Setting_IntValue) isSetting_Value() {}

func (*Setting_StringValue) isSetting_Value() {}

func (*Setting_BoolValue) isSetting_Value() {}

func (*Setting_SingleChoiceValue) isSetting_Value() {}

func (*Setting_MultiChoiceValue) isSetting_Value() {}

func (m *Setting) GetValue() isSetting_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Setting) GetIntValue() *IntSetting {
	if x, ok := m.GetValue().(*Setting_IntValue); ok {
		return x.IntValue
	}
	return nil
}

func (m *Setting) GetStringValue() *StringSetting {
	if x, ok := m.GetValue().(*Setting_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *Setting) GetBoolValue() *BoolSetting {
	if x, ok := m.GetValue().(*Setting_BoolValue); ok {
		return x.BoolValue
	}
	return nil
}

func (m *Setting) GetSingleChoiceValue() *SingleChoiceListSetting {
	if x, ok := m.GetValue().(*Setting_SingleChoiceValue); ok {
		return x.SingleChoiceValue
	}
	return nil
}

func (m *Setting) GetMultiChoiceValue() *MultiChoiceListSetting {
	if x, ok := m.GetValue().(*Setting_MultiChoiceValue); ok {
		return x.MultiChoiceValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Setting) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Setting_IntValue)(nil),
		(*Setting_StringValue)(nil),
		(*Setting_BoolValue)(nil),
		(*Setting_SingleChoiceValue)(nil),
		(*Setting_MultiChoiceValue)(nil),
	}
}

type IntSetting struct {
	Default              int64    `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Min                  int64    `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int64    `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Step                 int64    `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	Placeholder          string   `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntSetting) Reset()         { *m = IntSetting{} }
func (m *IntSetting) String() string { return proto.CompactTextString(m) }
func (*IntSetting) ProtoMessage()    {}
func (*IntSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{8}
}

func (m *IntSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntSetting.Unmarshal(m, b)
}
func (m *IntSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntSetting.Marshal(b, m, deterministic)
}
func (m *IntSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntSetting.Merge(m, src)
}
func (m *IntSetting) XXX_Size() int {
	return xxx_messageInfo_IntSetting.Size(m)
}
func (m *IntSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_IntSetting.DiscardUnknown(m)
}

var xxx_messageInfo_IntSetting proto.InternalMessageInfo

func (m *IntSetting) GetDefault() int64 {
	if m != nil {
		return m.Default
	}
	return 0
}

func (m *IntSetting) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *IntSetting) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *IntSetting) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *IntSetting) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

type StringSetting struct {
	Default              string   `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Required             bool     `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	MinLength            int32    `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	MaxLength            int32    `protobuf:"varint,4,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Placeholder          string   `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringSetting) Reset()         { *m = StringSetting{} }
func (m *StringSetting) String() string { return proto.CompactTextString(m) }
func (*StringSetting) ProtoMessage()    {}
func (*StringSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{9}
}

func (m *StringSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringSetting.Unmarshal(m, b)
}
func (m *StringSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringSetting.Marshal(b, m, deterministic)
}
func (m *StringSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringSetting.Merge(m, src)
}
func (m *StringSetting) XXX_Size() int {
	return xxx_messageInfo_StringSetting.Size(m)
}
func (m *StringSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_StringSetting.DiscardUnknown(m)
}

var xxx_messageInfo_StringSetting proto.InternalMessageInfo

func (m *StringSetting) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *StringSetting) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *StringSetting) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *StringSetting) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *StringSetting) GetPlaceholder() string {
	if m != nil {
		return m.Placeholder
	}
	return ""
}

type BoolSetting struct {
	Default              bool     `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolSetting) Reset()         { *m = BoolSetting{} }
func (m *BoolSetting) String() string { return proto.CompactTextString(m) }
func (*BoolSetting) ProtoMessage()    {}
func (*BoolSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{10}
}

func (m *BoolSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolSetting.Unmarshal(m, b)
}
func (m *BoolSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolSetting.Marshal(b, m, deterministic)
}
func (m *BoolSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolSetting.Merge(m, src)
}
func (m *BoolSetting) XXX_Size() int {
	return xxx_messageInfo_BoolSetting.Size(m)
}
func (m *BoolSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolSetting.DiscardUnknown(m)
}

var xxx_messageInfo_BoolSetting proto.InternalMessageInfo

func (m *BoolSetting) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type SingleChoiceListSetting struct {
	Options              []*ListOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SingleChoiceListSetting) Reset()         { *m = SingleChoiceListSetting{} }
func (m *SingleChoiceListSetting) String() string { return proto.CompactTextString(m) }
func (*SingleChoiceListSetting) ProtoMessage()    {}
func (*SingleChoiceListSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{11}
}

func (m *SingleChoiceListSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleChoiceListSetting.Unmarshal(m, b)
}
func (m *SingleChoiceListSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleChoiceListSetting.Marshal(b, m, deterministic)
}
func (m *SingleChoiceListSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleChoiceListSetting.Merge(m, src)
}
func (m *SingleChoiceListSetting) XXX_Size() int {
	return xxx_messageInfo_SingleChoiceListSetting.Size(m)
}
func (m *SingleChoiceListSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleChoiceListSetting.DiscardUnknown(m)
}

var xxx_messageInfo_SingleChoiceListSetting proto.InternalMessageInfo

func (m *SingleChoiceListSetting) GetOptions() []*ListOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type MultiChoiceListSetting struct {
	Options              []*ListOption `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MultiChoiceListSetting) Reset()         { *m = MultiChoiceListSetting{} }
func (m *MultiChoiceListSetting) String() string { return proto.CompactTextString(m) }
func (*MultiChoiceListSetting) ProtoMessage()    {}
func (*MultiChoiceListSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{12}
}

func (m *MultiChoiceListSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiChoiceListSetting.Unmarshal(m, b)
}
func (m *MultiChoiceListSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiChoiceListSetting.Marshal(b, m, deterministic)
}
func (m *MultiChoiceListSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiChoiceListSetting.Merge(m, src)
}
func (m *MultiChoiceListSetting) XXX_Size() int {
	return xxx_messageInfo_MultiChoiceListSetting.Size(m)
}
func (m *MultiChoiceListSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiChoiceListSetting.DiscardUnknown(m)
}

var xxx_messageInfo_MultiChoiceListSetting proto.InternalMessageInfo

func (m *MultiChoiceListSetting) GetOptions() []*ListOption {
	if m != nil {
		return m.Options
	}
	return nil
}

type ListOption struct {
	// Types that are valid to be assigned to Option:
	//	*ListOption_StringValue
	//	*ListOption_IntValue
	Option               isListOption_Option `protobuf_oneof:"option"`
	Selected             bool                `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	DisplayValue         string              `protobuf:"bytes,4,opt,name=display_value,json=displayValue,proto3" json:"display_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListOption) Reset()         { *m = ListOption{} }
func (m *ListOption) String() string { return proto.CompactTextString(m) }
func (*ListOption) ProtoMessage()    {}
func (*ListOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7cab62fa432213, []int{13}
}

func (m *ListOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOption.Unmarshal(m, b)
}
func (m *ListOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOption.Marshal(b, m, deterministic)
}
func (m *ListOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOption.Merge(m, src)
}
func (m *ListOption) XXX_Size() int {
	return xxx_messageInfo_ListOption.Size(m)
}
func (m *ListOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOption.DiscardUnknown(m)
}

var xxx_messageInfo_ListOption proto.InternalMessageInfo

type isListOption_Option interface {
	isListOption_Option()
}

type ListOption_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ListOption_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*ListOption_StringValue) isListOption_Option() {}

func (*ListOption_IntValue) isListOption_Option() {}

func (m *ListOption) GetOption() isListOption_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (m *ListOption) GetStringValue() string {
	if x, ok := m.GetOption().(*ListOption_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *ListOption) GetIntValue() int64 {
	if x, ok := m.GetOption().(*ListOption_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *ListOption) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *ListOption) GetDisplayValue() string {
	if m != nil {
		return m.DisplayValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListOption) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListOption_StringValue)(nil),
		(*ListOption_IntValue)(nil),
	}
}

func init() {
	proto.RegisterType((*CreateSettingsBundleRequest)(nil), "proto.CreateSettingsBundleRequest")
	proto.RegisterType((*CreateSettingsBundleResponse)(nil), "proto.CreateSettingsBundleResponse")
	proto.RegisterType((*GetSettingsBundleRequest)(nil), "proto.GetSettingsBundleRequest")
	proto.RegisterType((*GetSettingsBundleResponse)(nil), "proto.GetSettingsBundleResponse")
	proto.RegisterType((*ListSettingsBundlesRequest)(nil), "proto.ListSettingsBundlesRequest")
	proto.RegisterType((*ListSettingsBundlesResponse)(nil), "proto.ListSettingsBundlesResponse")
	proto.RegisterType((*SettingsBundle)(nil), "proto.SettingsBundle")
	proto.RegisterType((*Setting)(nil), "proto.Setting")
	proto.RegisterType((*IntSetting)(nil), "proto.IntSetting")
	proto.RegisterType((*StringSetting)(nil), "proto.StringSetting")
	proto.RegisterType((*BoolSetting)(nil), "proto.BoolSetting")
	proto.RegisterType((*SingleChoiceListSetting)(nil), "proto.SingleChoiceListSetting")
	proto.RegisterType((*MultiChoiceListSetting)(nil), "proto.MultiChoiceListSetting")
	proto.RegisterType((*ListOption)(nil), "proto.ListOption")
}

func init() {
	proto.RegisterFile("settings.proto", fileDescriptor_6c7cab62fa432213)
}

var fileDescriptor_6c7cab62fa432213 = []byte{
	// 983 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x6f, 0xdc, 0x44,
	0x14, 0xae, 0x77, 0x73, 0xd9, 0x3d, 0x69, 0x6e, 0xd3, 0x40, 0x17, 0x37, 0x81, 0x8d, 0xf3, 0x00,
	0x0d, 0x64, 0x1d, 0x92, 0x27, 0x22, 0x81, 0xda, 0x84, 0x90, 0x14, 0x92, 0x52, 0x39, 0x12, 0x0f,
	0x20, 0x58, 0xcd, 0x7a, 0x07, 0xef, 0x50, 0x7b, 0xc6, 0xf5, 0x8c, 0x73, 0x51, 0x54, 0x09, 0x78,
	0xe1, 0x11, 0x09, 0x1e, 0x79, 0x43, 0xe2, 0x0d, 0xf8, 0x33, 0xfc, 0x05, 0x7e, 0x08, 0xf2, 0xf1,
	0xd8, 0x7b, 0xc9, 0x26, 0xb4, 0x82, 0x27, 0x7b, 0xce, 0xf9, 0xbe, 0xef, 0x7c, 0x9e, 0x33, 0x17,
	0xc3, 0x9c, 0x62, 0x5a, 0x73, 0x11, 0xa8, 0x56, 0x9c, 0x48, 0x2d, 0xc9, 0x24, 0x3e, 0xec, 0xe5,
	0x40, 0xca, 0x20, 0x64, 0x2e, 0x8d, 0xb9, 0x4b, 0x85, 0x90, 0x9a, 0x6a, 0x2e, 0x85, 0x01, 0xd9,
	0xef, 0xe0, 0xc3, 0xdf, 0x08, 0x98, 0xd8, 0x50, 0x67, 0x34, 0x08, 0x58, 0xe2, 0xca, 0x18, 0x11,
	0x57, 0xd1, 0xce, 0x97, 0x70, 0x6f, 0x2f, 0x61, 0x54, 0xb3, 0x13, 0x53, 0x6a, 0x37, 0x15, 0xdd,
	0x90, 0x79, 0xec, 0x59, 0xca, 0x94, 0x26, 0x1f, 0xc0, 0x7c, 0xe1, 0xa1, 0xdd, 0xc1, 0x4c, 0xc3,
	0x6a, 0x5a, 0x6f, 0xcd, 0x6c, 0xbd, 0x92, 0xf3, 0x5b, 0x23, 0xb4, 0xd2, 0x71, 0x3e, 0x76, 0xbe,
	0x82, 0xe5, 0xf1, 0xf2, 0x2a, 0x96, 0x42, 0xb1, 0xff, 0xac, 0xff, 0x31, 0x34, 0x0e, 0x98, 0x1e,
	0xef, 0x7d, 0x19, 0xea, 0xec, 0x5c, 0x33, 0xa1, 0xb8, 0x14, 0xa8, 0x5a, 0xf7, 0xfa, 0x01, 0xb2,
	0x00, 0xd5, 0xa7, 0xec, 0xa2, 0x51, 0xc1, 0x78, 0xf6, 0xea, 0x7c, 0x01, 0xaf, 0x8d, 0xd1, 0xfa,
	0x9f, 0x8c, 0xee, 0x80, 0x7d, 0xc4, 0xd5, 0x88, 0xba, 0x7a, 0x21, 0xab, 0x4e, 0x1b, 0xee, 0x8d,
	0xe5, 0x1a, 0x6b, 0x0f, 0x60, 0x61, 0xc4, 0x9a, 0x6a, 0x58, 0xcd, 0xea, 0xf5, 0xde, 0xe6, 0x87,
	0xbd, 0x29, 0xe7, 0x47, 0x0b, 0xe6, 0x86, 0x31, 0x2f, 0x3b, 0x79, 0x64, 0x15, 0x6e, 0x77, 0xb9,
	0x8a, 0x43, 0x7a, 0xd1, 0x16, 0x34, 0x62, 0x8d, 0x2a, 0xa6, 0x66, 0x4c, 0xec, 0x31, 0x8d, 0x18,
	0x59, 0x87, 0x5a, 0x51, 0xb8, 0x31, 0x81, 0xfe, 0xe6, 0x86, 0xfd, 0x79, 0x65, 0xde, 0xf9, 0xbd,
	0x0a, 0xd3, 0x26, 0x5a, 0x14, 0xb3, 0xae, 0x2f, 0x56, 0xb9, 0x5a, 0xac, 0x09, 0x33, 0x5d, 0xa6,
	0xfc, 0x84, 0xe3, 0xca, 0x2f, 0xed, 0xf4, 0x43, 0x64, 0x13, 0xea, 0x5c, 0xe8, 0xf6, 0x29, 0x0d,
	0x53, 0xd6, 0x98, 0xc0, 0x5e, 0x2e, 0x1a, 0x3f, 0x8f, 0x44, 0x31, 0xd9, 0x87, 0xb7, 0xbc, 0x1a,
	0x17, 0xfa, 0xb3, 0x0c, 0x44, 0xde, 0x83, 0xdb, 0x4a, 0x27, 0x5c, 0x04, 0x86, 0x34, 0x89, 0xa4,
	0xa5, 0xe2, 0x23, 0x30, 0xd5, 0xe7, 0xcd, 0xe4, 0xd8, 0x9c, 0xba, 0x0d, 0xd0, 0x91, 0x32, 0x34,
	0xc4, 0x29, 0x24, 0x12, 0x43, 0xdc, 0x95, 0x32, 0xec, 0xd3, 0xea, 0x19, 0x2e, 0x27, 0x3d, 0x81,
	0x3b, 0x8a, 0x8b, 0x20, 0x64, 0x6d, 0xbf, 0x27, 0xb9, 0xcf, 0x0c, 0x7b, 0x1a, 0xd9, 0xaf, 0x17,
	0x65, 0x11, 0xb1, 0x87, 0x80, 0x81, 0x55, 0x72, 0x78, 0xcb, 0x5b, 0x54, 0x03, 0xa9, 0x5c, 0xf1,
	0x18, 0x48, 0x94, 0x86, 0x9a, 0x0f, 0x0b, 0xd6, 0x50, 0x70, 0xc5, 0x08, 0x1e, 0x67, 0x80, 0x71,
	0x7a, 0x0b, 0x51, 0x3f, 0x83, 0x72, 0xbb, 0xd3, 0x30, 0x89, 0x0a, 0xce, 0xb7, 0x16, 0x40, 0x7f,
	0xd2, 0x48, 0x03, 0xa6, 0xbb, 0xec, 0x6b, 0x9a, 0x86, 0x1a, 0xbb, 0x56, 0xf5, 0x8a, 0x61, 0xd6,
	0xcb, 0x88, 0x0b, 0x6c, 0x58, 0xd5, 0xcb, 0x5e, 0x31, 0x42, 0xcf, 0xb1, 0x41, 0x59, 0x84, 0x9e,
	0x13, 0x02, 0x13, 0x4a, 0xb3, 0x18, 0x7b, 0x52, 0xf5, 0xf0, 0x3d, 0x6b, 0x67, 0x1c, 0x52, 0x9f,
	0xf5, 0x64, 0xd8, 0x65, 0x09, 0xce, 0x7c, 0xdd, 0x1b, 0x0c, 0x39, 0xbf, 0x59, 0x30, 0x3b, 0xd4,
	0x82, 0x51, 0x17, 0xf5, 0xbe, 0x0b, 0x1b, 0x6a, 0x09, 0x7b, 0x96, 0xf2, 0x84, 0x75, 0xd1, 0x4a,
	0xcd, 0x2b, 0xc7, 0x64, 0x05, 0x20, 0xe2, 0xa2, 0x1d, 0x32, 0x11, 0xe8, 0x1e, 0xda, 0x9a, 0xf4,
	0xea, 0x11, 0x17, 0x47, 0x18, 0xc0, 0x34, 0x3d, 0x2f, 0xd2, 0x13, 0x26, 0x4d, 0xcf, 0x4d, 0xfa,
	0xdf, 0x7d, 0xbe, 0x09, 0x33, 0x03, 0x0d, 0x1f, 0x35, 0x59, 0x2b, 0x4d, 0x3a, 0x1f, 0xc1, 0xdd,
	0x6b, 0x7a, 0x4b, 0xde, 0x86, 0x69, 0x73, 0xa2, 0x9b, 0x8d, 0x5e, 0x2c, 0xdc, 0x0c, 0xf4, 0x29,
	0x66, 0xbc, 0x02, 0xe1, 0xec, 0xc3, 0xab, 0xe3, 0x5b, 0xfa, 0x72, 0x32, 0xbf, 0x58, 0x00, 0xfd,
	0x38, 0x59, 0x1b, 0xd9, 0x0b, 0x38, 0xc3, 0xa3, 0xab, 0x7e, 0x65, 0x70, 0x8b, 0x61, 0xcf, 0x87,
	0xf6, 0x93, 0x9d, 0x1d, 0x08, 0x21, 0xf3, 0x35, 0xeb, 0xe2, 0x44, 0xd7, 0xbc, 0x72, 0x4c, 0xd6,
	0x60, 0xb6, 0xd8, 0xe2, 0xfd, 0x1d, 0x5a, 0xf7, 0x8a, 0x7d, 0x9f, 0xaf, 0xbf, 0x1a, 0x4c, 0xe5,
	0xf6, 0xb6, 0x7e, 0xa8, 0xc2, 0x6c, 0x7e, 0x72, 0x9d, 0xb0, 0xe4, 0x94, 0xfb, 0x8c, 0x5c, 0xc2,
	0xd2, 0xb8, 0x9b, 0x87, 0x38, 0xe6, 0x1b, 0x6f, 0xb8, 0xf5, 0xec, 0xb5, 0x1b, 0x31, 0xf9, 0xb1,
	0xeb, 0xd8, 0xdf, 0xff, 0xf5, 0xf7, 0xcf, 0x95, 0x25, 0x67, 0x1e, 0xef, 0xe1, 0xd3, 0x4d, 0xd7,
	0x9c, 0xbd, 0x3b, 0xd6, 0x3a, 0xf9, 0xce, 0x82, 0xc5, 0x2b, 0x77, 0x09, 0x79, 0xc3, 0xc8, 0x5e,
	0x77, 0x63, 0xd9, 0xcd, 0xeb, 0x01, 0xa6, 0xe8, 0x7d, 0x2c, 0xba, 0x46, 0x56, 0x47, 0x8a, 0xba,
	0x97, 0xe5, 0xe1, 0xfc, 0xdc, 0xbd, 0x7c, 0xca, 0x2e, 0x9e, 0x93, 0x14, 0xee, 0x8c, 0xb9, 0x35,
	0xc8, 0xea, 0x40, 0x8f, 0xc7, 0xdf, 0x46, 0xb6, 0x73, 0x13, 0xc4, 0x18, 0xb9, 0x8b, 0x46, 0x16,
	0xc9, 0xe8, 0xd7, 0xef, 0xfe, 0x51, 0xf9, 0xe9, 0xe1, 0xaf, 0x15, 0xf2, 0xa7, 0x05, 0xb5, 0x82,
	0xeb, 0x3c, 0x81, 0x59, 0x79, 0x26, 0xf6, 0x42, 0x99, 0x76, 0x9b, 0x07, 0x51, 0xe7, 0x90, 0xdc,
	0xef, 0x69, 0x1d, 0xab, 0x1d, 0xd7, 0x0d, 0xb8, 0xee, 0xa5, 0x9d, 0x96, 0x2f, 0x23, 0x57, 0x9e,
	0x09, 0x3f, 0x43, 0xb8, 0xd2, 0xe7, 0x6a, 0xa3, 0xb8, 0x09, 0xec, 0x25, 0x95, 0xc6, 0xb1, 0x4c,
	0xf4, 0x83, 0x22, 0x9f, 0x81, 0xd7, 0x3f, 0x01, 0x78, 0x18, 0x53, 0xbf, 0xc7, 0x36, 0xb6, 0x5a,
	0x9b, 0xe4, 0xfd, 0x17, 0x96, 0x73, 0x3b, 0xa1, 0xec, 0xb8, 0x11, 0x55, 0x9a, 0x25, 0xee, 0xd1,
	0xa3, 0xbd, 0xfd, 0xc7, 0x27, 0xfb, 0x5b, 0xd5, 0x77, 0x5b, 0x9b, 0xeb, 0x15, 0xab, 0xb2, 0xb5,
	0x40, 0xe3, 0x38, 0xe4, 0x3e, 0xfe, 0x20, 0xb9, 0xdf, 0x28, 0x29, 0x76, 0xae, 0x44, 0x92, 0x03,
	0x58, 0xf8, 0x90, 0x9d, 0xb2, 0x50, 0xc6, 0x2c, 0x69, 0x1e, 0x53, 0x91, 0xd2, 0x90, 0x6c, 0x67,
	0xf5, 0x77, 0xdc, 0xb2, 0x66, 0xcb, 0xf8, 0xe0, 0xd2, 0x2d, 0xdb, 0xa2, 0xd0, 0x48, 0xbb, 0x34,
	0xf2, 0x79, 0xfe, 0x33, 0xd7, 0x99, 0xc2, 0xc7, 0xf6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26,
	0x84, 0x87, 0xe6, 0xec, 0x09, 0x00, 0x00,
}
