//Please also make language adjustments in packages/web-pkg/src/components/TextEditor/l18n.ts

export const supportedLanguages = {
  af: 'Afrikaans - Afrikaans',
  ar: 'العربية - Arabic',
  bs: 'Bosanski - Bosnian',
  bg: 'български - Bulgarian',
  ca: 'Català - Catalan',
  cs: 'Čeština - Czech',
  de: 'Deutsch - German',
  el: 'Ελληνικά - Greek',
  en: 'English',
  es: 'Español - Spanish',
  et: 'Eesti - Estonian',
  fr: 'Français - French',
  gl: 'Galego - Galician',
  he: 'עברית - Hebrew',
  hr: 'Hrvatski - Croatian',
  id: 'Bahasa Indonesia - Indonesian',
  it: 'Italiano - Italian',
  ja: '日本語 - Japanese',
  nl: 'Nederlands - Dutch',
  pl: 'Polski - Polish',
  pt: 'Português - Portuguese',
  ka: 'ქართული - Georgian',
  ko: '한국어 - Korean',
  ro: 'Română - Romanian',
  ru: 'русский - Russian',
  si: 'සිංහල - Sinhala',
  sk: 'Slovenčina - Slovak',
  sq: 'Shqipja - Albanian',
  sv: 'Svenska - Swedish',
  sr: 'српски - Serbian',
  ta: 'தமிழ் - Tamil',
  tr: 'Türkçe - Turkish',
  ug: 'ئۇيغۇرچە - Uyghur',
  uk: 'українська - Ukrainian',
  zh: '汉语 - Chinese'
}
