FROM arm64v8/alpine:latest

RUN apk update && \
	apk upgrade && \
	apk add ca-certificates mailcap && \
	rm -rf /var/cache/apk/* && \
	echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="oCIS Web" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

EXPOSE 9100 9104

ENTRYPOINT ["/usr/bin/ocis-web"]
CMD ["server"]

COPY bin/ocis-web /usr/bin/ocis-web
