issues:
  exclude-rules:
    - path: pkg/proto/v0
      text: "SA1019:"
      linters:
        - staticcheck
linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - depguard
    - revive
    - goimports
    - unconvert
    - scopelint
    - maligned
    - misspell
    - gocritic
    - prealloc
    #- gosec
