// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	providerv1beta1 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"

	userv1beta1 "github.com/cs3org/go-cs3apis/cs3/identity/user/v1beta1"
)

// Retriever is an autogenerated mock type for the Retriever type
type Retriever struct {
	mock.Mock
}

// Retrieve provides a mock function with given fields: ctx, ref, owner
func (_m *Retriever) Retrieve(ctx context.Context, ref *providerv1beta1.Reference, owner *userv1beta1.User) (io.ReadCloser, error) {
	ret := _m.Called(ctx, ref, owner)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(context.Context, *providerv1beta1.Reference, *userv1beta1.User) io.ReadCloser); ok {
		r0 = rf(ctx, ref, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *providerv1beta1.Reference, *userv1beta1.User) error); ok {
		r1 = rf(ctx, ref, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRetriever interface {
	mock.TestingT
	Cleanup(func())
}

// NewRetriever creates a new instance of Retriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRetriever(t mockConstructorTestingTNewRetriever) *Retriever {
	mock := &Retriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
