---
services:
  ocis:
    depends_on:
      externalsites-init:
        condition: service_completed_successfully

  externalsites-init:
    image: owncloud/web-extensions:external-sites-0.3.0
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/external-sites/ /apps"]
