with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/owncloud/ocis/v2/services/collaboration/pkg/connector:
        config:
            dir: "mocks"
        interfaces:
            ConnectorService:
            ContentConnectorService:
            FileConnectorService:
    github.com/owncloud/ocis/v2/services/collaboration/pkg/locks:
        config:
            dir: "mocks"
        interfaces:
            LockParser:
    github.com/cs3org/reva/v2/pkg/rgrpc/todo/pool:
        config:
            dir: "mocks"
        interfaces:
            Selectable:
                config:
                    filename: "gateway_selector.go"
