---
services:
  ocis:
    volumes:
      - ./config/ocis/apps.yaml:/etc/ocis/apps.yaml
    depends_on:
      chat-with-file-init:
        condition: service_completed_successfully

  chat-with-file-init:
    image: owncloud/web-extensions:chat-with-file-0.1.0
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/chat-with-file/ /apps"]
