---
services:
  ocis:
    volumes:
      - ./config/ocis/apps.yaml:/etc/ocis/apps.yaml
    depends_on:
      externalsites-init:
        condition: service_completed_successfully

  externalsites-init:
    image: owncloud/web-extensions:external-sites-0.3.3@sha256:88bbc188996ef4d42dbb530da938206e610237e117a5a76d54321437072acb42
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/external-sites/ /apps"]
