---
services:
  ocis:
    depends_on:
      progressbars-init:
        condition: service_completed_successfully

  progressbars-init:
    image: owncloud/web-extensions:progress-bars-0.3.2@sha256:9878254320ae30d52910c6d9153899a4a1ce46e428fcd90b36dfc1bb80dc223a
    platform: linux/${IMAGE_ARCH:-amd64}
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/progress-bars/ /apps"]
