---
services:
  ocis:
    configs:
      - source: apps_yaml
        target: /etc/ocis/apps.yaml
    depends_on:
      version-changelog-init:
        condition: service_completed_successfully

  version-changelog-init:
    image: owncloud/web-extensions:version-changelog-0.1.0
    user: root
    volumes:
      - ocis-apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /var/lib/nginx/html/version-changelog/ /apps"]
