FROM arm32v6/alpine:edge

RUN apk update && \
	apk upgrade && \
	apk add ca-certificates mailcap && \
	rm -rf /var/cache/apk/* && \
	echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="oCIS Reva" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

EXPOSE 9135 9136

ENTRYPOINT ["/usr/bin/ocis-reva"]
CMD ["server"]

COPY bin/ocis-reva /usr/bin/ocis-reva
