package config

func MetadataDrivers(cfg *Config) map[string]interface{} {
	return map[string]interface{}{
		"eos": map[string]interface{}{
			"namespace":              cfg.Drivers.EOS.Root,
			"shadow_namespace":       cfg.Drivers.EOS.ShadowNamespace,
			"uploads_namespace":      cfg.Drivers.EOS.UploadsNamespace,
			"eos_binary":             cfg.Drivers.EOS.EosBinary,
			"xrdcopy_binary":         cfg.Drivers.EOS.XrdcopyBinary,
			"master_url":             cfg.Drivers.EOS.MasterURL,
			"slave_url":              cfg.Drivers.EOS.SlaveURL,
			"cache_directory":        cfg.Drivers.EOS.CacheDirectory,
			"sec_protocol":           cfg.Drivers.EOS.SecProtocol,
			"keytab":                 cfg.Drivers.EOS.Keytab,
			"single_username":        cfg.Drivers.EOS.SingleUsername,
			"enable_logging":         cfg.Drivers.EOS.EnableLogging,
			"show_hidden_sys_files":  cfg.Drivers.EOS.ShowHiddenSysFiles,
			"force_single_user_mode": cfg.Drivers.EOS.ForceSingleUserMode,
			"use_keytab":             cfg.Drivers.EOS.UseKeytab,
			"gatewaysvc":             cfg.Drivers.EOS.GatewaySVC,
			"enable_home":            false,
		},
		"eosgrpc": map[string]interface{}{
			"namespace":              cfg.Drivers.EOS.Root,
			"shadow_namespace":       cfg.Drivers.EOS.ShadowNamespace,
			"eos_binary":             cfg.Drivers.EOS.EosBinary,
			"xrdcopy_binary":         cfg.Drivers.EOS.XrdcopyBinary,
			"master_url":             cfg.Drivers.EOS.MasterURL,
			"master_grpc_uri":        cfg.Drivers.EOS.GRPCURI,
			"slave_url":              cfg.Drivers.EOS.SlaveURL,
			"cache_directory":        cfg.Drivers.EOS.CacheDirectory,
			"sec_protocol":           cfg.Drivers.EOS.SecProtocol,
			"keytab":                 cfg.Drivers.EOS.Keytab,
			"single_username":        cfg.Drivers.EOS.SingleUsername,
			"user_layout":            cfg.Drivers.EOS.UserLayout,
			"enable_logging":         cfg.Drivers.EOS.EnableLogging,
			"show_hidden_sys_files":  cfg.Drivers.EOS.ShowHiddenSysFiles,
			"force_single_user_mode": cfg.Drivers.EOS.ForceSingleUserMode,
			"use_keytab":             cfg.Drivers.EOS.UseKeytab,
			"enable_home":            false,
			"gatewaysvc":             cfg.Drivers.EOS.GatewaySVC,
		},
		"local": map[string]interface{}{
			"root": cfg.Drivers.Local.Root,
		},
		"ocis": map[string]interface{}{
			"root":                cfg.Drivers.OCIS.Root,
			"user_layout":         cfg.Drivers.OCIS.UserLayout,
			"treetime_accounting": false,
			"treesize_accounting": false,
			"permissionssvc":      cfg.GRPC.Addr,
		},
		"s3": map[string]interface{}{
			"region":     cfg.Drivers.S3.Region,
			"access_key": cfg.Drivers.S3.AccessKey,
			"secret_key": cfg.Drivers.S3.SecretKey,
			"endpoint":   cfg.Drivers.S3.Endpoint,
			"bucket":     cfg.Drivers.S3.Bucket,
		},
		"s3ng": map[string]interface{}{
			"root":                cfg.Drivers.S3NG.Root,
			"enable_home":         false,
			"user_layout":         cfg.Drivers.S3NG.UserLayout,
			"treetime_accounting": false,
			"treesize_accounting": false,
			"permissionssvc":      cfg.Drivers.S3NG.PermissionsEndpoint,
			"s3.region":           cfg.Drivers.S3NG.Region,
			"s3.access_key":       cfg.Drivers.S3NG.AccessKey,
			"s3.secret_key":       cfg.Drivers.S3NG.SecretKey,
			"s3.endpoint":         cfg.Drivers.S3NG.Endpoint,
			"s3.bucket":           cfg.Drivers.S3NG.Bucket,
		},
	}
}
