with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
dir: "pkg/{{.PackageName}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/owncloud/ocis/v2/services/search/pkg/engine:
        interfaces:
            Engine:
    github.com/owncloud/ocis/v2/services/search/pkg/content:
        interfaces:
            Extractor:
            Retriever:
    github.com/owncloud/ocis/v2/services/search/pkg/search:
        interfaces:
            Searcher: