---
- name: continuous-deployment-ocis-production
  server:
    server_type: cx22
    image: ubuntu-24.04
    location: nbg1
    initial_ssh_key_names:
      - owncloud-ocis@drone.owncloud.com
    labels:
      owner: ocis-team
      for: oCIS-continuous-deployment-examples
    rebuild: $REBUILD
    rebuild_carry_paths:
      - /var/lib/docker/volumes/ocis_certs

  domains:
    - "*.ocis.production.owncloud.works"

  vars:
    ssh_authorized_keys:
      - https://github.com/kobergj.keys
      - https://github.com/2403905.keys
      - https://github.com/d7oc.keys
      - https://github.com/wkloucek.keys
    docker_compose_projects:
      - name: ocis
        git_url: https://github.com/owncloud/ocis.git
        ref: master
        docker_compose_path: deployments/examples/ocis_full
        env:
          INSECURE: "false"
          TRAEFIK_ACME_MAIL: julian.koberg@kiteworks.com
          OCIS_DOCKER_TAG: 7.0.0
          OCIS_DOMAIN: ocis.ocis.production.owncloud.works
          COMPANION_DOMAIN: companion.ocis.production.owncloud.works
          COMPANION_IMAGE: owncloud/uppy-companion:3.12.13-owncloud
          WOPISERVER_DOMAIN: wopiserver.ocis.production.owncloud.works
          COLLABORA_DOMAIN: collabora.ocis.production.owncloud.works
          MAIL_SERVER_DOMAIN: mail.ocis.production.owncloud.works
          DEMO_USERS: "true"
          COMPOSE_FILE: docker-compose.yml:ocis.yml:tika.yml:collabora.yml:web_extensions/extensions.yml:web_extensions/unzip.yml:web_extensions/importer.yml:mailserver.yml:monitoring_tracing/monitoring.yml
      - name: monitoring
        git_url: https://github.com/owncloud-devops/monitoring-tracing-client.git
        ref: master
        env:
          NETWORK_NAME: ocis-net
          TELEMETRY_SERVE_DOMAIN: telemetry.ocis.production.owncloud.works
          JAEGER_COLLECTOR: jaeger-collector.infra.owncloud.works:443
          TELEGRAF_SPECIFIC_CONFIG: ocis_wopi
          OCIS_URL: ocis.ocis.production.owncloud.works
          OCIS_DEPLOYMENT_ID: continuous-deployment-ocis-production
