// Code generated by protoc-gen-microweb. DO NOT EDIT.
// source: proto.proto

package proto

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/render"
	merrors "go-micro.dev/v4/errors"
	"google.golang.org/protobuf/encoding/protojson"

	ptypesempty "github.com/golang/protobuf/ptypes/empty"
)

type webGreeterHandler struct {
	r chi.Router
	h GreeterHandler
}

func (h *webGreeterHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	h.r.ServeHTTP(w, r)
}

func (h *webGreeterHandler) Say(w http.ResponseWriter, r *http.Request) {
	req := &SayRequest{}
	resp := &SayResponse{}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusPreconditionFailed)
		return
	}

	if err := h.h.Say(
		r.Context(),
		req,
		resp,
	); err != nil {
		if merr, ok := merrors.As(err); ok && merr.Code == http.StatusNotFound {
			http.Error(w, err.Error(), http.StatusNotFound)
		} else {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
		return
	}

	render.Status(r, http.StatusCreated)
	render.JSON(w, r, resp)
}

func (h *webGreeterHandler) SayAnything(w http.ResponseWriter, r *http.Request) {
	req := &ptypesempty.Empty{}
	resp := &SayResponse{}

	if err := h.h.SayAnything(
		r.Context(),
		req,
		resp,
	); err != nil {
		if merr, ok := merrors.As(err); ok && merr.Code == http.StatusNotFound {
			http.Error(w, err.Error(), http.StatusNotFound)
		} else {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
		return
	}

	render.Status(r, http.StatusCreated)
	render.JSON(w, r, resp)
}

func RegisterGreeterWeb(r chi.Router, i GreeterHandler, middlewares ...func(http.Handler) http.Handler) {
	handler := &webGreeterHandler{
		r: r,
		h: i,
	}

	r.MethodFunc("POST", "/api/say", handler.Say)
	r.MethodFunc("POST", "/api/anything", handler.SayAnything)
}

// SayRequestJSONMarshaler describes the default protojson.Marshaler used by all
// instances of SayRequest. This struct is safe to replace or modify but
// should not be done so concurrently.
var SayRequestJSONMarshaler = protojson.MarshalOptions{}

// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct protojson package to correctly marshal the message.
func (m *SayRequest) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}

	return SayRequestJSONMarshaler.Marshal(m)
}

var _ json.Marshaler = (*SayRequest)(nil)

// SayRequestJSONUnmarshaler describes the default protojson.Unmarshaler used by all
// instances of SayRequest. This struct is safe to replace or modify but
// should not be done so concurrently.
var SayRequestJSONUnmarshaler = protojson.UnmarshalOptions{}

// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct protojson package to correctly unmarshal the message.
func (m *SayRequest) UnmarshalJSON(b []byte) error {
	return SayRequestJSONUnmarshaler.Unmarshal(b, m)
}

var _ json.Unmarshaler = (*SayRequest)(nil)

// SayResponseJSONMarshaler describes the default protojson.Marshaler used by all
// instances of SayResponse. This struct is safe to replace or modify but
// should not be done so concurrently.
var SayResponseJSONMarshaler = protojson.MarshalOptions{}

// MarshalJSON satisfies the encoding/json Marshaler interface. This method
// uses the more correct protojson package to correctly marshal the message.
func (m *SayResponse) MarshalJSON() ([]byte, error) {
	if m == nil {
		return json.Marshal(nil)
	}

	return SayResponseJSONMarshaler.Marshal(m)
}

var _ json.Marshaler = (*SayResponse)(nil)

// SayResponseJSONUnmarshaler describes the default protojson.Unmarshaler used by all
// instances of SayResponse. This struct is safe to replace or modify but
// should not be done so concurrently.
var SayResponseJSONUnmarshaler = protojson.UnmarshalOptions{}

// UnmarshalJSON satisfies the encoding/json Unmarshaler interface. This method
// uses the more correct protojson package to correctly unmarshal the message.
func (m *SayResponse) UnmarshalJSON(b []byte) error {
	return SayResponseJSONUnmarshaler.Unmarshal(b, m)
}

var _ json.Unmarshaler = (*SayResponse)(nil)
