with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/owncloud/ocis/v2/ocis-pkg/keycloak:
        config:
            dir: "pkg/backends/keycloak/mocks"
        interfaces:
            Client: