---
policy_selector:
  claims:
    default_policy: oc10
    unauthenticated_policy: oc10
policies:
  - name: ocis
    routes:
      - endpoint: /
        backend: http://localhost:9100
      - endpoint: /.well-known/
        backend: http://localhost:9130
      - endpoint: /konnect/
        backend: http://localhost:9130
      - endpoint: /signin/
        backend: http://localhost:9130
      - endpoint: /archiver
        backend: http://localhost:9140
      - type: regex
        endpoint: /ocs/v[12].php/cloud/user/signing-key
        backend: http://localhost:9110
      - endpoint: /ocs/
        backend: http://localhost:9140
      - type: query
        endpoint: /remote.php/?preview=1
        backend: http://localhost:9115
      - method: REPORT
        endpoint: /remote.php/dav/
        backend: http://localhost:9115
      - type: query
        endpoint: /dav/?preview=1
        backend: http://localhost:9115
      - type: query
        endpoint: /webdav/?preview=1
        backend: http://localhost:9115
      - endpoint: /remote.php/
        service: com.owncloud.web.ocdav
      - endpoint: /dav/
        service: com.owncloud.web.ocdav
      - endpoint: /webdav/
        service: com.owncloud.web.ocdav
      - endpoint: /status.php
        service: com.owncloud.web.ocdav
      - endpoint: /index.php/
        service: com.owncloud.web.ocdav
      - endpoint: /apps/
        service: com.owncloud.web.ocdav
      - endpoint: /data
        backend: http://localhost:9140
      - endpoint: /app/
        backend: http://localhost:9140
      - endpoint: /graph/
        backend: http://localhost:9120
      - endpoint: /api/v0/settings
        backend: http://localhost:9190
  - name: oc10
    routes:
      - endpoint: "/"
        backend: http://oc10:8080
      - endpoint: "/data"
        backend: http://localhost:9140
