FROM amd64/alpine:edge

RUN apk update && \
	apk upgrade && \
	apk add ca-certificates mailcap && \
	rm -rf /var/cache/apk/* && \
	echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="oCIS Onlyoffice" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

EXPOSE 9220 9224

ENTRYPOINT ["/usr/bin/ocis-onlyoffice"]
CMD ["server"]

COPY bin/ocis-onlyoffice /usr/bin/ocis-onlyoffice
