<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit47d0a653801ac6ad887ff504bf59ed54
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Bamarni\\Composer\\Bin\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit47d0a653801ac6ad887ff504bf59ed54::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit47d0a653801ac6ad887ff504bf59ed54::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit47d0a653801ac6ad887ff504bf59ed54::$classMap;

        }, null, ClassLoader::class);
    }
}
