---
version: "3.7"

services:
  ocis:
    environment:
      LDAP_GROUP_BASE_DN: "ou=TestGroups,dc=owncloud,dc=com"
      LDAP_USER_BASE_DN: "ou=TestUsers,dc=owncloud,dc=com"
      PROXY_ENABLE_BASIC_AUTH: "true"

  oc10:
    ports:
      - 8080:8080
    volumes:
      - ./config/oc10/11-testing-app.sh:/etc/pre_server.d/11-testing-app.sh

  openldap:
    ports:
      - 636:636
