FROM arm64v8/alpine:3.12

RUN apk update && \
	apk upgrade && \
	apk add ca-certificates mailcap && \
	rm -rf /var/cache/apk/* && \
	echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.label-schema.name="ownCloud Infinite Scale" \
  org.label-schema.vendor="ownCloud GmbH" \
  org.label-schema.schema-version="1.0"

EXPOSE 9200/tcp

ENTRYPOINT ["/usr/bin/ocis"]
CMD ["server"]

COPY bin/ocis /usr/bin/ocis

VOLUME [ "/var/tmp/ocis" ]
