// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/owncloud/ocis/search/pkg/search"
	mock "github.com/stretchr/testify/mock"
)

// IndexClient is an autogenerated mock type for the IndexClient type
type IndexClient struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, req
func (_m *IndexClient) Search(ctx context.Context, req *search.SearchIndexRequest) (*search.SearchIndexResult, error) {
	ret := _m.Called(ctx, req)

	var r0 *search.SearchIndexResult
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchIndexRequest) *search.SearchIndexResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchIndexResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchIndexRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
