// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	search "github.com/owncloud/ocis/search/pkg/search"
	mock "github.com/stretchr/testify/mock"
)

// ProviderClient is an autogenerated mock type for the ProviderClient type
type ProviderClient struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, req
func (_m *ProviderClient) Search(ctx context.Context, req *search.SearchRequest) (*search.SearchResult, error) {
	ret := _m.Called(ctx, req)

	var r0 *search.SearchResult
	if rf, ok := ret.Get(0).(func(context.Context, *search.SearchRequest) *search.SearchResult); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*search.SearchResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *search.SearchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
