depends_on:
  - build_ocis_binary_for_testing
platform:
  arch: amd64
  os: linux
steps:
  - image: owncloudci/drone-skip-pipeline
    name: skip-if-unchanged
    settings:
      ALLOW_SKIP_CHANGED:
        - ^.github/.*
        - ^.vscode/.*
        - ^changelog/.*
        - ^docs/.*
        - ^deployments/.*
        - CHANGELOG.md
        - CONTRIBUTING.md
        - LICENSE
        - README.md
        - .*_test.go$
    when:
      event:
        - pull_request
  - image: plugins/s3-cache:1
    name: restore_ocis-binary-amd64_build_artifact_cache
    settings:
      access_key:
        from_secret: cache_s3_access_key
      endpoint: https://cache.owncloud.com
      fallback_path: cache/opencloud-eu/opencloud/-${DRONE_BUILD_NUMBER}
      filename: ocis-binary-amd64_build_artifact_cache.tar
      mount:
        - ocis/bin
      path: cache/opencloud-eu/opencloud/-${DRONE_BUILD_NUMBER}
      rebuild: "false"
      restore: "true"
      secret_key:
        from_secret: cache_s3_secret_key
  - commands:
      - mkdir -p $GOCOVERDIR
      - ocis/bin/ocis-debug init --insecure true
      - cat $OCIS_CONFIG_DIR/ocis.yaml
      - cp tests/config/drone/app-registry.yaml /root/.ocis/config/app-registry.yaml
      - ocis/bin/ocis-debug server
    depends_on: []
    detach: true
    environment:
      ACTIVITYLOG_DEBUG_ADDR: 0.0.0.0:9197
      APP_PROVIDER_DEBUG_ADDR: 0.0.0.0:9165
      APP_REGISTRY_DEBUG_ADDR: 0.0.0.0:9243
      AUTH_BASIC_DEBUG_ADDR: 0.0.0.0:9147
      AUTH_MACHINE_DEBUG_ADDR: 0.0.0.0:9167
      AUTH_SERVICE_DEBUG_ADDR: 0.0.0.0:9198
      CLIENTLOG_DEBUG_ADDR: 0.0.0.0:9260
      EVENTHISTORY_DEBUG_ADDR: 0.0.0.0:9270
      EVENTHISTORY_STORE: memory
      FRONTEND_DEBUG_ADDR: 0.0.0.0:9141
      FRONTEND_SEARCH_MIN_LENGTH: "2"
      GATEWAY_DEBUG_ADDR: 0.0.0.0:9143
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      GOCOVERDIR: reports
      GRAPH_DEBUG_ADDR: 0.0.0.0:9124
      GROUPS_DEBUG_ADDR: 0.0.0.0:9161
      IDM_ADMIN_PASSWORD: admin
      IDM_CREATE_DEMO_USERS: true
      IDM_DEBUG_ADDR: 0.0.0.0:9239
      IDP_DEBUG_ADDR: 0.0.0.0:9134
      INVITATIONS_DEBUG_ADDR: 0.0.0.0:9269
      NATS_DEBUG_ADDR: 0.0.0.0:9234
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      OCDAV_DEBUG_ADDR: 0.0.0.0:9163
      OCIS_ASYNC_UPLOADS: true
      OCIS_CONFIG_DIR: /root/.ocis/config
      OCIS_EVENTS_ENABLE_TLS: false
      OCIS_JWT_SECRET: some-ocis-jwt-secret
      OCIS_LOG_LEVEL: error
      OCIS_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: false
      OCIS_TRANSLATION_PATH: /drone/src/tests/config/translations
      OCIS_URL: https://ocis-server:9200
      OCM_DEBUG_ADDR: 0.0.0.0:9281
      OCS_DEBUG_ADDR: 0.0.0.0:9114
      POSTPROCESSING_DEBUG_ADDR: 0.0.0.0:9255
      PROXY_DEBUG_ADDR: 0.0.0.0:9205
      PROXY_ENABLE_BASIC_AUTH: true
      SEARCH_DEBUG_ADDR: 0.0.0.0:9224
      SETTINGS_DEBUG_ADDR: 0.0.0.0:9194
      SHARING_DEBUG_ADDR: 0.0.0.0:9151
      SSE_DEBUG_ADDR: 0.0.0.0:9139
      STORAGE_PUBLICLINK_DEBUG_ADDR: 0.0.0.0:9179
      STORAGE_SHARES_DEBUG_ADDR: 0.0.0.0:9156
      STORAGE_SYSTEM_DEBUG_ADDR: 0.0.0.0:9217
      STORAGE_USERS_DEBUG_ADDR: 0.0.0.0:9159
      STORAGE_USERS_DRIVER: ocis
      THUMBNAILS_DEBUG_ADDR: 0.0.0.0:9189
      USERLOG_DEBUG_ADDR: 0.0.0.0:9214
      USERS_DEBUG_ADDR: 0.0.0.0:9145
      WEB_DEBUG_ADDR: 0.0.0.0:9104
      WEB_UI_CONFIG_FILE: /drone/src/tests/config/drone/ocis-config.json
      WEBDAV_DEBUG_ADDR: 0.0.0.0:9119
      WEBFINGER_DEBUG_ADDR: 0.0.0.0:9279
    image: owncloudci/golang:1.24
    name: ocis-server
    user: "0:0"
    volumes: []
  - commands:
      - timeout 300 bash -c 'while [ $(curl -sk -uadmin:admin https://ocis-server:9200/graph/v1.0/users/admin -w %{http_code} -o /dev/null) != 200 ]; do sleep 1; done'
    depends_on: []
    image: owncloudci/alpine:latest
    name: wait-for-ocis-server
  - commands:
      - /usr/bin/cs3api-validator /var/lib/cs3api-validator --endpoint=ocis-server:9142
    environment: {}
    image: owncloud/cs3api-validator:0.2.1
    name: cs3ApiTests
trigger:
  ref:
    - refs/heads/master
    - refs/heads/stable-*
    - refs/pull/**
