depends_on:
  - get-go-bin-cache
kind: pipeline
platform:
  arch: amd64
  os: linux
steps:
  - image: owncloudci/drone-skip-pipeline
    name: skip-if-unchanged
    settings:
      ALLOW_SKIP_CHANGED:
        - ^.github/.*
        - ^.vscode/.*
        - ^changelog/.*
        - ^docs/.*
        - ^deployments/.*
        - CHANGELOG.md
        - CONTRIBUTING.md
        - LICENSE
        - README.md
        - ^tests/acceptance/.*
    when:
      event:
        - pull_request
  - commands:
      - BINGO_HASH=$(cat /drone/src/.bingo/* | sha256sum | cut -d ' ' -f 1)
      - mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -r -a s3/$CACHE_BUCKET/ocis/go-bin/$BINGO_HASH/go-bin.tar.gz /drone/src
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      CACHE_BUCKET: cache
      MC_HOST: https://cache.owncloud.com
    image: minio/mc:RELEASE.2021-10-07T04-19-58Z
    name: restore-go-bin-cache
    volumes:
      - name: gopath
        path: /go
  - commands:
      - tar -xvmf /drone/src/go-bin.tar.gz -C /
    image: owncloud/ubuntu:20.04
    name: extract-go-bin-cache
    volumes:
      - name: gopath
        path: /go
  - commands:
      - retry -t 3 'make ci-go-generate'
    environment:
      HTTP_PROXY:
        from_secret: drone_http_proxy
      HTTPS_PROXY:
        from_secret: drone_http_proxy
    image: owncloudci/golang:1.24
    name: generate go
    volumes:
      - name: gopath
        path: /go
  - commands:
      - mkdir -p cache/checkstyle
      - make ci-golangci-lint
      - mv checkstyle.xml cache/checkstyle/checkstyle.xml
    environment:
      HTTP_PROXY:
        from_secret: drone_http_proxy
      HTTPS_PROXY:
        from_secret: drone_http_proxy
    image: owncloudci/golang:1.24
    name: golangci-lint
    volumes:
      - name: gopath
        path: /go
  - commands:
      - mkdir -p cache/coverage
      - make test
      - mv coverage.out cache/coverage/
    environment:
      HTTP_PROXY:
        from_secret: drone_http_proxy
      HTTPS_PROXY:
        from_secret: drone_http_proxy
    image: owncloudci/golang:1.24
    name: test
    volumes:
      - name: gopath
        path: /go
  - image: plugins/s3:1
    name: scan-result-cache
    settings:
      access_key:
        from_secret: cache_s3_access_key
      bucket: cache
      endpoint: https://cache.owncloud.com
      path_style: true
      secret_key:
        from_secret: cache_s3_secret_key
      source: cache/**/*
      target: opencloud-eu/opencloud/-${DRONE_BUILD_NUMBER}
trigger:
  ref:
    - refs/heads/master
    - refs/heads/stable-*
    - refs/pull/**
type: docker
volumes:
  - name: gopath
    temp: {}
