name: Acceptance Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Build ocis
        run: make -C ocis build

      - name: Unit tests
        run: make test

  acceptance-tests:
    name: ${{ matrix.suite }}
    needs: [build-and-test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          # graph
          - apiGraph
          - apiGraphGroup
          - apiGraphUser
          # spaces & dav
          - apiSpaces
          - apiSpacesShares
          - apiSpacesDavOperation
          - apiDownloads
          - apiAsyncUpload
          - apiDepthInfinity
          - apiArchiver
          - apiActivities
          # search
          - apiSearch1
          # contract & locks
          - apiLocks
          # sharing
          - apiSharingNgItemInvitation
          - apiSharingNgPermissions
          - apiSharingNgShares
          - apiSharingNgAdditionalShareRole
          - apiSharingNgDriveInvitation
          - apiSharingNgItemLinkShare
          - apiSharingNgDriveLinkShare
          - apiSharingNgLinkShareManagement
          
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod
          cache: true

      - uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: "8.4"
          extensions: curl, xml, mbstring, zip
          tools: composer

      - name: Run ${{ matrix.suite }}
        run: BEHAT_SUITES=${{ matrix.suite }} bash tests/acceptance/run-github.sh

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: test-logs-${{ matrix.suite }}
          path: tests/acceptance/output/

  all-acceptance-tests:
    needs: [build-and-test, acceptance-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check all jobs passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
