name: Check licenses
on:
  pull_request:
  push:
    branches: [master, stable-*]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install REUSE tool
        run: pip install reuse

      - name: Run REUSE lint
        run: reuse lint
