name: Translation Sync

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync:
    uses: owncloud/reusable-workflows/.github/workflows/translation-sync.yml@main
    with:
      mode: make
      reviewers: kobergj,mmattel          # individual users
      # team_reviewers: owncloud/ocis-team  # and/or a GitHub team slug if exists
      sub_path: .
    secrets:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
      TRANSLATION_APP_ID: ${{ secrets.TRANSLATION_APP_ID }}
      TRANSLATION_APP_PRIVATE_KEY: ${{ secrets.TRANSLATION_APP_PRIVATE_KEY }}
